import type { Descuento } from "./beneficios";

export const data: Descuento[] = [
    {
        "ciudad": "Antofagasta",
        "dia": "Martes",
        "proveedor": "Banco Itaú",
        "tienda": "FOGO",
        "descuento": 20,
        "producto": "Tarjeta de débito",
    },
    {
        "ciudad": "Antofagasta",
        "dia": "Miércoles",
        "proveedor": "Santander (sin límite)",
        "tienda": "CLIB de Yates",
        "descuento": 20,
        "producto": "Tarjeta de débito",
    },
    {
        "ciudad": "Antofagasta",
        "dia": "Miércoles",
        "proveedor": "Scotiabank",
        "tienda": "Steakhouse",
        "descuento": 20,
        "producto": "Tarjeta de débito",
    },
    {
        "ciudad": "Antofagasta",
        "dia": "Jueves",
        "proveedor": "Banco Bice",
        "tienda": "BRUNNIT",
        "descuento": 20,
        "producto": "Tarjeta de débito",
    },
    {
        "ciudad": "Antofagasta",
        "dia": "Jueves",
        "proveedor": "Banco Ripley",
        "tienda": "De Rock & Burger",
        "descuento": 20,
        "producto": "Tarjeta de débito",
    },
    {
        "ciudad": "Antofagasta",
        "dia": "Viernes",
        "proveedor": "BCI",
        "tienda": "Ámbar Restobar",
        "descuento": 20,
        "producto": "Tarjeta de débito",
    },
    {
        "ciudad": "Arica",
        "dia": "Martes",
        "proveedor": "Banco de Chile",
        "tienda": "Tuto Beach",
        "descuento": 40,
        "producto": "Tarjeta de débito",
    },
    {
        "ciudad": "Arica",
        "dia": "Martes",
        "proveedor": "Banco Ripley",
        "tienda": "Bar de Lobos",
        "descuento": 40,
        "producto": "Tarjeta de débito",
    },
    {
        "ciudad": "Arica",
        "dia": "Martes",
        "proveedor": "Security",
        "tienda": "La Pasta de la Nonna",
        "descuento": 40,
        "producto": "Tarjeta de débito",
    },
    {
        "ciudad": "Arica",
        "dia": "Miércoles",
        "proveedor": "CMR",
        "tienda": "G14",
        "descuento": 40,
        "producto": "Tarjeta de débito",
    },
    {
        "ciudad": "Arica",
        "dia": "Miércoles",
        "proveedor": "Scotiabank",
        "tienda": "Terramola",
        "descuento": 40,
        "producto": "Tarjeta de débito",
    },
    {
        "ciudad": "Arica",
        "dia": "Jueves",
        "proveedor": "Banco Bice",
        "tienda": "La Pasta de la Nonna",
        "descuento": 40,
        "producto": "Tarjeta de débito",
    },
    {
        "ciudad": "Arica",
        "dia": "Viernes",
        "proveedor": "BCI",
        "tienda": "Rosa Amelia",
        "descuento": 40,
        "producto": "Tarjeta de débito",
    },
    {
        "ciudad": "Concón",
        "dia": "Miércoles",
        "proveedor": "Banco de Chile",
        "tienda": "Los Hornitos",
        "descuento": 40,
        "producto": "Tarjeta de débito",
    },
    {
        "ciudad": "Curacaví",
        "dia": "Miércoles",
        "proveedor": "Santander",
        "tienda": "Raymi",
        "descuento": 40,
        "producto": "Tarjeta de débito",
    },
    {
        "ciudad": "Frutillar",
        "dia": "Miércoles",
        "proveedor": "CMR",
        "tienda": "Fugas del Mar",
        "descuento": 40,
        "producto": "Tarjeta de débito",
    },
    {
        "ciudad": "Iquique",
        "dia": "Martes",
        "proveedor": "Banco Itaú",
        "tienda": "Yado by Asia",
        "descuento": 40,
        "producto": "Tarjeta de débito",
    },
    {
        "ciudad": "Iquique",
        "dia": "Martes",
        "proveedor": "Santander (sin límite)",
        "tienda": "Piso 21",
        "descuento": 40,
        "producto": "Tarjeta de débito",
    },
    {
        "ciudad": "Iquique",
        "dia": "Miércoles",
        "proveedor": "Scotiabank",
        "tienda": "Dominga Bistró",
        "descuento": 40,
        "producto": "Tarjeta de débito",
    },
    {
        "ciudad": "Iquique",
        "dia": "Jueves",
        "proveedor": "BCI",
        "tienda": "La Mulata",
        "descuento": 40,
        "producto": "Tarjeta de débito",
    },
    {
        "ciudad": "La Serena",
        "dia": "Martes",
        "proveedor": "Banco Itaú",
        "tienda": "Terrazza",
        "descuento": 40,
        "producto": "Tarjeta de crédito",
    },
    {
        "ciudad": "La Serena",
        "dia": "Martes",
        "proveedor": "Santander (sin límite)",
        "tienda": "Tollo Beach",
        "descuento": 40,
        "producto": "Tarjeta de crédito",
    },
    {
        "ciudad": "La Serena",
        "dia": "Martes",
        "proveedor": "Security",
        "tienda": "Hotel Costa Real",
        "descuento": 40,
        "producto": "Tarjeta de crédito",
    },
    {
        "ciudad": "La Serena",
        "dia": "Jueves",
        "proveedor": "Santander",
        "tienda": "Zona Zero",
        "descuento": 40,
        "producto": "Tarjeta de crédito",
    },
    {
        "ciudad": "Los Ángeles",
        "dia": "Martes",
        "proveedor": "Banco Itaú",
        "tienda": "Bife Sureño",
        "descuento": 40,
        "producto": "Tarjeta de crédito",
    },
    {
        "ciudad": "Machalí",
        "dia": "Martes",
        "proveedor": "Banco Itaú",
        "tienda": "La Hacienda Machalí",
        "descuento": 40,
        "producto": "Tarjeta de crédito",
    },
    {
        "ciudad": "Matencillo",
        "dia": "Miércoles",
        "proveedor": "Santander Amex",
        "tienda": "La Pesca",
        "descuento": 50,
        "producto": "Tarjeta de crédito",
    },
    {
        "ciudad": "Osorno",
        "dia": "Martes",
        "proveedor": "Banco Itaú",
        "tienda": "El Galpón",
        "descuento": 40,
        "producto": "Tarjeta de crédito",
    },
    {
        "ciudad": "Osorno",
        "dia": "Jueves",
        "proveedor": "Banco Bice",
        "tienda": "Greed",
        "descuento": 40,
        "producto": "Tarjeta de crédito",
    },
    {
        "ciudad": "Pichilemu",
        "dia": "Viernes",
        "proveedor": "BCI",
        "tienda": "Bocas del Mar",
        "descuento": 40,
        "producto": "Tarjeta de crédito",
    },
    {
        "ciudad": "Pichilemu",
        "dia": "Martes",
        "proveedor": "Security",
        "tienda": "Camalache",
        "descuento": 40,
        "producto": "Tarjeta de crédito",
    },
    {
        "ciudad": "Puerto Varas",
        "dia": "Martes",
        "proveedor": "Santander",
        "tienda": "Hotel Awa",
        "descuento": 40,
        "producto": "Tarjeta de crédito",
    },
    {
        "ciudad": "Puerto Montt",
        "dia": "Jueves",
        "proveedor": "Banco Bice",
        "tienda": "Hotel Bellavista",
        "descuento": 40,
        "producto": "Tarjeta de crédito",
    },
    {
        "ciudad": "Puerto Montt",
        "dia": "Viernes",
        "proveedor": "BCI",
        "tienda": "Da Alessandro",
        "descuento": 40,
        "producto": "Tarjeta de crédito",
    },
    {
        "ciudad": "Rancagua/Machalí",
        "dia": "Jueves",
        "proveedor": "Banco Itaú",
        "tienda": "Da Alessandro",
        "descuento": 40,
        "producto": "Tarjeta de crédito",
    },
    {
        "ciudad": "Rancagua/Machalí",
        "dia": "Jueves",
        "proveedor": "Banco Bice",
        "tienda": "Don Teo",
        "descuento": 40,
        "producto": "Tarjeta de crédito",
    },
    {
        "ciudad": "Reñaca",
        "dia": "Miércoles",
        "proveedor": "Santander Amex",
        "tienda": "SUMOKU",
        "descuento": 50,
        "producto": "Tarjeta de crédito",
    },
    {
        "ciudad": "Reñaca/Viña",
        "dia": "Jueves",
        "proveedor": "BCI",
        "tienda": "INSOMNIO",
        "descuento": 60,
        "producto": "Tarjeta de crédito",
    },
    {
        "ciudad": "San Fernando",
        "dia": "Jueves",
        "proveedor": "Scotiabank",
        "tienda": "Sarzones",
        "descuento": 60,
        "producto": "Tarjeta de crédito",
    },
    {
        "ciudad": "San Pedro de la Paz",
        "dia": "Miércoles",
        "proveedor": "Santander (sin límite)",
        "tienda": "Augusta Bar",
        "descuento": 60,
        "producto": "Tarjeta de crédito",
    },
    {
        "ciudad": "San Pedro de la Paz",
        "dia": "Viernes",
        "proveedor": "Scotiabank",
        "tienda": "La Barra Restobar",
        "descuento": 60,
        "producto": "Tarjeta de crédito",
    },
    {
        "ciudad": "Santa Cruz",
        "dia": "Domingo",
        "proveedor": "Banco de Chile",
        "tienda": "Noi Blend",
        "descuento": 60,
        "producto": "Tarjeta de crédito",
    },
    {
        "ciudad": "Santa Cruz",
        "dia": "Martes",
        "proveedor": "Santander",
        "tienda": "Casa Albergue",
        "descuento": 60,
        "producto": "Tarjeta de crédito",
    },
    {
        "ciudad": "Santa Cruz",
        "dia": "Miércoles",
        "proveedor": "Security",
        "tienda": "La Fábrica",
        "descuento": 60,
        "producto": "Tarjeta de crédito",
    },
    {
        "ciudad": "Santa Cruz",
        "dia": "Viernes",
        "proveedor": "Banco de Chile",
        "tienda": "Carnes Domo",
        "descuento": 60,
        "producto": "Tarjeta de crédito",
    },
    {
        "ciudad": "Talca",
        "dia": "Martes",
        "proveedor": "Banco Itaú",
        "tienda": "La Fuente Italiana",
        "descuento": 60,
        "producto": "Tarjeta de crédito",
    },
    {
        "ciudad": "Talca",
        "dia": "Miércoles",
        "proveedor": "Banco de Chile",
        "tienda": "Sushi House",
        "descuento": 60,
        "producto": "Tarjeta de crédito",
    },
    {
        "ciudad": "Talca",
        "dia": "Viernes",
        "proveedor": "Santander (sin límite)",
        "tienda": "Radho",
        "descuento": 60,
        "producto": "Tarjeta de crédito",
    },
    {
        "ciudad": "Temuco",
        "dia": "Miércoles",
        "proveedor": "Santander",
        "tienda": "León de San Martin",
        "descuento": 60,
        "producto": "Tarjeta de crédito",
    },
    {
        "ciudad": "Temuco",
        "dia": "Jueves",
        "proveedor": "BCI",
        "tienda": "Hashigo",
        "descuento": 60,
        "producto": "Tarjeta de crédito",
    },
    {
        "ciudad": "Temuco",
        "dia": "Viernes",
        "proveedor": "Banco de Chile",
        "tienda": "Secret Garden",
        "descuento": 60,
        "producto": "Tarjeta de crédito",
    },
    {
        "ciudad": "Tomé",
        "dia": "Viernes",
        "proveedor": "Banco de Chile",
        "tienda": "Icaro",
        "descuento": 40,
        "producto": "Tarjeta de crédito",
    },
    {
        "ciudad": "Valdivia",
        "dia": "Viernes",
        "proveedor": "Banco de Chile",
        "tienda": "Riviera Poke",
        "descuento": 40,
        "producto": "Tarjeta de crédito",
    },
    {
        "ciudad": "Valdivia",
        "dia": "Miércoles",
        "proveedor": "Banco de Chile",
        "tienda": "La Parrilla de Thor",
        "descuento": 40,
        "producto": "Tarjeta de crédito",
    },
    {
        "ciudad": "Valparaíso",
        "dia": "Lunes",
        "proveedor": "Banco Itaú",
        "tienda": "Sazón Peruano",
        "descuento": 40,
        "producto": "Tarjeta de crédito",
    },
    {
        "ciudad": "Valparaíso",
        "dia": "Miércoles",
        "proveedor": "Scotiabank",
        "tienda": "Puerto Claro",
        "descuento": 20,
        "producto": "Tarjeta de crédito",
    },
    {
        "ciudad": "Viña del Mar",
        "dia": "Martes",
        "proveedor": "Banco Ripley",
        "tienda": "Lima 51",
        "descuento": 20,
        "producto": "Tarjeta de crédito",
    },
    {
        "ciudad": "Viña del Mar",
        "dia": "Miércoles",
        "proveedor": "Santander (sin límite)",
        "tienda": "Hotel Sheraton",
        "descuento": 20,
        "producto": "Tarjeta de crédito",
    },
    {
        "ciudad": "Viña del Mar",
        "dia": "Viernes",
        "proveedor": "BCI",
        "tienda": "Valentini's",
        "descuento": 20,
        "producto": "Tarjeta de crédito",
    },
    {
        "ciudad": "Mall Marina",
        "dia": "Lunes a Viernes",
        "proveedor": "CMR",
        "tienda": "Luna Vieja",
        "descuento": 20,
        "producto": "Tarjeta de crédito",
    },
    {
        "ciudad": "Viña/Coquimbo",
        "dia": "Miércoles",
        "proveedor": "Santander",
        "tienda": "Sibarac",
        "descuento": 20,
        "producto": "Tarjeta de crédito",
    },
    {
        "ciudad": "Mall Marina",
        "dia": "Lunes a Viernes",
        "proveedor": "CMR",
        "tienda": "Sanguchería del B.",
        "descuento": 20,
        "producto": "Tarjeta de crédito",
    }
]
    ;