import type { Descuento } from "./beneficios";

export function obtenerDescuentos(): Descuento[] {
    const descuentos: Descuento[] = [];

    const meses: string[] = [
        "enero",
        "febrero",
        "marzo",
        "abril",
        "mayo",
        "junio",
        "julio",
        "agosto",
        "septiembre",
        "octubre",
        "noviembre",
        "diciembre",
    ];

    try {
        for (const fila of filas) {
            const descuento = Number(
                fila["Descuento"]
                    .replaceAll("$", "")
                    .replaceAll(".", "")
                    .replaceAll("%", "")
                    .replaceAll(" ", "")
            );

            const ordenMes = meses.indexOf(fila["Mes"]) + 1;
            const productos = fila["Producto"].replaceAll(", ", ",").split(",");
            const dias = fila["Día"].replaceAll(", ", ",").split(",");

            for (const producto of productos) {
                for (const dia of dias) {
                    descuentos.push({
                        ano: Number(fila["Año"]),
                        ciudad: fila["Ciudad"],
                        descuento: descuento,
                        dia: dia,
                        mes: fila["Mes"],
                        ordenMes: ordenMes,
                        producto: producto,
                        proveedor: fila["Institución Financiera"],
                        tienda: fila["Local"],
                    });
                }
            }
        }
    } catch (error) {
        console.error("error al obtener descuentos", error);
    }

    return descuentos;
}

const filas = [
    {
        "Año": "2024",
        "Mes": "Septiembre",
        "Ciudad": "Santiago",
        "Día": "Miércoles",
        "Institución Financiera": "Banco Santander",
        "Producto": "T. Crédito",
        "Marca de Tarjeta": "Todas",
        "Segmento": "Todos",
        "Local": "Casa Morera",
        "Descuento": "40%",
        "Tope Descuento": "$40.000",
        "Observación": "",
        "Info": "https://banco.santander.cl/beneficios/promociones/casa-morera-2"
    },
    {
        "Año": "2024",
        "Mes": "Septiembre",
        "Ciudad": "Santiago",
        "Día": "Miércoles",
        "Institución Financiera": "Banco Santander",
        "Producto": "T. Crédito",
        "Marca de Tarjeta": "Todas",
        "Segmento": "Todos",
        "Local": "Do Sushi",
        "Descuento": "40%",
        "Tope Descuento": "$40.000",
        "Observación": "",
        "Info": "https://banco.santander.cl/landing/beneficios-descuentos"
    },
    {
        "Año": "2024",
        "Mes": "Septiembre",
        "Ciudad": "Santiago",
        "Día": "Miércoles",
        "Institución Financiera": "Banco Santander",
        "Producto": "T. Crédito",
        "Marca de Tarjeta": "Todas",
        "Segmento": "Todos",
        "Local": "Hijo Del Sol",
        "Descuento": "40%",
        "Tope Descuento": "$40.000",
        "Observación": "",
        "Info": "https://banco.santander.cl/beneficios/promociones/hijo-del-sol-2"
    },
    {
        "Año": "2024",
        "Mes": "Septiembre",
        "Ciudad": "Santiago",
        "Día": "Miércoles",
        "Institución Financiera": "Banco Santander",
        "Producto": "T. Crédito",
        "Marca de Tarjeta": "Todas",
        "Segmento": "Todos",
        "Local": "La Burguesía",
        "Descuento": "40%",
        "Tope Descuento": "$40.000",
        "Observación": "",
        "Info": "https://banco.santander.cl/beneficios/promociones/la-burguesia"
    },
    {
        "Año": "2024",
        "Mes": "Septiembre",
        "Ciudad": "Santiago",
        "Día": "Miércoles",
        "Institución Financiera": "Banco Santander",
        "Producto": "T. Crédito",
        "Marca de Tarjeta": "Todas",
        "Segmento": "Todos",
        "Local": "La Cocina De Javier",
        "Descuento": "40%",
        "Tope Descuento": "$40.000",
        "Observación": "",
        "Info": "https://banco.santander.cl/beneficios/promociones/la-cocina-de-javier"
    },
    {
        "Año": "2024",
        "Mes": "Septiembre",
        "Ciudad": "Santiago",
        "Día": "Miércoles",
        "Institución Financiera": "Banco Santander",
        "Producto": "T. Crédito",
        "Marca de Tarjeta": "Todas",
        "Segmento": "Todos",
        "Local": "Local Burger",
        "Descuento": "40%",
        "Tope Descuento": "$40.000",
        "Observación": "",
        "Info": "https://banco.santander.cl/beneficios/promociones/local-burger-2"
    },
    {
        "Año": "2024",
        "Mes": "Septiembre",
        "Ciudad": "Santiago",
        "Día": "Miércoles",
        "Institución Financiera": "Banco Santander",
        "Producto": "T. Crédito",
        "Marca de Tarjeta": "Todas",
        "Segmento": "Todos",
        "Local": "Pf Chang's",
        "Descuento": "40%",
        "Tope Descuento": "$40.000",
        "Observación": "",
        "Info": "https://banco.santander.cl/beneficios/promociones/pfchang"
    },
    {
        "Año": "2024",
        "Mes": "Septiembre",
        "Ciudad": "Santiago",
        "Día": "Miércoles",
        "Institución Financiera": "Banco Santander",
        "Producto": "T. Crédito",
        "Marca de Tarjeta": "Todas",
        "Segmento": "Todos",
        "Local": "Prima Bar",
        "Descuento": "40%",
        "Tope Descuento": "$40.000",
        "Observación": "",
        "Info": "https://banco.santander.cl/beneficios/promociones/prima-bar-3"
    },
    {
        "Año": "2024",
        "Mes": "Septiembre",
        "Ciudad": "Santiago",
        "Día": "Miércoles",
        "Institución Financiera": "Banco Santander",
        "Producto": "T. Crédito",
        "Marca de Tarjeta": "Todas",
        "Segmento": "Todos",
        "Local": "Santa Brasa",
        "Descuento": "40%",
        "Tope Descuento": "$40.000",
        "Observación": "",
        "Info": "https://banco.santander.cl/beneficios/promociones/santa-brasa-2"
    },
    {
        "Año": "2024",
        "Mes": "Septiembre",
        "Ciudad": "Santiago",
        "Día": "Miércoles",
        "Institución Financiera": "Banco Santander",
        "Producto": "T. Crédito",
        "Marca de Tarjeta": "Todas",
        "Segmento": "Todos",
        "Local": "Soul Of India",
        "Descuento": "40%",
        "Tope Descuento": "$40.000",
        "Observación": "",
        "Info": "https://banco.santander.cl/beneficios/promociones/santa-brasa-2"
    },
    {
        "Año": "2024",
        "Mes": "Septiembre",
        "Ciudad": "Santiago",
        "Día": "Viernes",
        "Institución Financiera": "Banco Santander",
        "Producto": "T. Crédito",
        "Marca de Tarjeta": "Todas",
        "Segmento": "Todos",
        "Local": "Sakura",
        "Descuento": "40%",
        "Tope Descuento": "$40.000",
        "Observación": "Solo en Rolls y Hosomaki",
        "Info": "https://banco.santander.cl/beneficios/promociones/sakura-4"
    },
    {
        "Año": "2024",
        "Mes": "Septiembre",
        "Ciudad": "Santiago",
        "Día": "Viernes",
        "Institución Financiera": "Banco Santander",
        "Producto": "T. Débito",
        "Marca de Tarjeta": "Todas",
        "Segmento": "-",
        "Local": "Sakura",
        "Descuento": "40%",
        "Tope Descuento": "$40.000",
        "Observación": "Solo en Rolls y Hosomaki",
        "Info": "https://banco.santander.cl/beneficios/promociones/sakura-4"
    },
    {
        "Año": "2024",
        "Mes": "Septiembre",
        "Ciudad": "Santiago",
        "Día": "Lunes",
        "Institución Financiera": "Banco Santander",
        "Producto": "T. Crédito",
        "Marca de Tarjeta": "VISA, AMEX",
        "Segmento": "WorldMember Limited",
        "Local": "La Dicha",
        "Descuento": "40%",
        "Tope Descuento": "$100.000",
        "Observación": "",
        "Info": "https://banco.santander.cl/landing/beneficios-descuentos"
    },
    {
        "Año": "2024",
        "Mes": "Septiembre",
        "Ciudad": "Santiago",
        "Día": "Martes",
        "Institución Financiera": "Banco Santander",
        "Producto": "T. Crédito",
        "Marca de Tarjeta": "VISA, AMEX",
        "Segmento": "WorldMember Limited",
        "Local": "Tomata",
        "Descuento": "40%",
        "Tope Descuento": "$100.000",
        "Observación": "",
        "Info": "https://banco.santander.cl/landing/beneficios-descuentos"
    },
    {
        "Año": "2024",
        "Mes": "Septiembre",
        "Ciudad": "Santiago",
        "Día": "Miércoles",
        "Institución Financiera": "Banco Santander",
        "Producto": "T. Crédito",
        "Marca de Tarjeta": "VISA, AMEX",
        "Segmento": "WorldMember Limited",
        "Local": "La Picantería",
        "Descuento": "40%",
        "Tope Descuento": "$100.000",
        "Observación": "",
        "Info": "https://banco.santander.cl/landing/beneficios-descuentos"
    },
    {
        "Año": "2024",
        "Mes": "Septiembre",
        "Ciudad": "Santiago",
        "Día": "Miércoles",
        "Institución Financiera": "Banco Santander",
        "Producto": "T. Crédito",
        "Marca de Tarjeta": "VISA, AMEX",
        "Segmento": "WorldMember Limited",
        "Local": "Piegari",
        "Descuento": "40%",
        "Tope Descuento": "$100.000",
        "Observación": "",
        "Info": "https://banco.santander.cl/landing/beneficios-descuentos"
    },
    {
        "Año": "2024",
        "Mes": "Septiembre",
        "Ciudad": "Santiago",
        "Día": "Jueves",
        "Institución Financiera": "Banco Santander",
        "Producto": "T. Crédito",
        "Marca de Tarjeta": "VISA, AMEX",
        "Segmento": "WorldMember Limited",
        "Local": "Pescados Capitales",
        "Descuento": "40%",
        "Tope Descuento": "$100.000",
        "Observación": "",
        "Info": "https://banco.santander.cl/beneficios/promociones/pescados-capitales-3"
    },
    {
        "Año": "2024",
        "Mes": "Septiembre",
        "Ciudad": "Santiago",
        "Día": "Lunes",
        "Institución Financiera": "Banco Santander",
        "Producto": "T. Crédito",
        "Marca de Tarjeta": "AMEX",
        "Segmento": "Todos",
        "Local": "Carnal",
        "Descuento": "50%",
        "Tope Descuento": "$50.000",
        "Observación": "",
        "Info": "https://banco.santander.cl/beneficios/promociones/carnal-2"
    },
    {
        "Año": "2024",
        "Mes": "Septiembre",
        "Ciudad": "Santiago",
        "Día": "Martes",
        "Institución Financiera": "Banco Santander",
        "Producto": "T. Crédito",
        "Marca de Tarjeta": "AMEX",
        "Segmento": "Todos",
        "Local": "Jardín Mallinkrodt",
        "Descuento": "50%",
        "Tope Descuento": "$50.000",
        "Observación": "",
        "Info": "https://banco.santander.cl/beneficios/promociones/jardin-mallinkrodt"
    },
    {
        "Año": "2024",
        "Mes": "Septiembre",
        "Ciudad": "Santiago",
        "Día": "Miércoles",
        "Institución Financiera": "Banco Santander",
        "Producto": "T. Crédito",
        "Marca de Tarjeta": "AMEX",
        "Segmento": "Todos",
        "Local": "Bar 99",
        "Descuento": "50%",
        "Tope Descuento": "$50.000",
        "Observación": "",
        "Info": "https://banco.santander.cl/beneficios/promociones/99-restaurante"
    },
    {
        "Año": "2024",
        "Mes": "Septiembre",
        "Ciudad": "Santiago",
        "Día": "Jueves",
        "Institución Financiera": "Banco Santander",
        "Producto": "T. Crédito",
        "Marca de Tarjeta": "AMEX",
        "Segmento": "Todos",
        "Local": "Yma",
        "Descuento": "50%",
        "Tope Descuento": "$50.000",
        "Observación": "",
        "Info": "https://banco.santander.cl/personas/tarjetas/promociones/amexforfoodies"
    },
    {
        "Año": "2024",
        "Mes": "Septiembre",
        "Ciudad": "Santiago",
        "Día": "Viernes",
        "Institución Financiera": "Banco Santander",
        "Producto": "T. Crédito",
        "Marca de Tarjeta": "AMEX",
        "Segmento": "Todos",
        "Local": "Otaki",
        "Descuento": "50%",
        "Tope Descuento": "$50.000",
        "Observación": "",
        "Info": "https://banco.santander.cl/beneficios/promociones/otaki-2"
    },
    {
        "Año": "2024",
        "Mes": "Septiembre",
        "Ciudad": "Santiago",
        "Día": "Sábado",
        "Institución Financiera": "Banco Santander",
        "Producto": "T. Crédito",
        "Marca de Tarjeta": "AMEX",
        "Segmento": "Todos",
        "Local": "Sabor Y Aroma",
        "Descuento": "50%",
        "Tope Descuento": "$50.000",
        "Observación": "",
        "Info": "https://banco.santander.cl/personas/tarjetas/promociones/amexforfoodies"
    },
    {
        "Año": "2024",
        "Mes": "Septiembre",
        "Ciudad": "Santiago",
        "Día": "Domingo",
        "Institución Financiera": "Banco Santander",
        "Producto": "T. Crédito",
        "Marca de Tarjeta": "AMEX",
        "Segmento": "Todos",
        "Local": "Gi Restaurant",
        "Descuento": "50%",
        "Tope Descuento": "$50.000",
        "Observación": "",
        "Info": "https://banco.santander.cl/beneficios/promociones/gi"
    },
    {
        "Año": "2024",
        "Mes": "Septiembre",
        "Ciudad": "Santiago",
        "Día": "Lunes",
        "Institución Financiera": "Banco BICE",
        "Producto": "T. Crédito",
        "Marca de Tarjeta": "VISA",
        "Segmento": "Todos",
        "Local": "Ambrosía",
        "Descuento": "40%",
        "Tope Descuento": "$50.000",
        "Observación": "",
        "Info": "https://banco.bice.cl/personas/beneficios/ambrosia"
    },
    {
        "Año": "2024",
        "Mes": "Septiembre",
        "Ciudad": "Santiago",
        "Día": "Martes",
        "Institución Financiera": "Banco BICE",
        "Producto": "T. Crédito",
        "Marca de Tarjeta": "VISA",
        "Segmento": "Todos",
        "Local": "El Establo",
        "Descuento": "40%",
        "Tope Descuento": "$50.000",
        "Observación": "",
        "Info": "https://banco.bice.cl/personas/beneficios/el-establo"
    },
    {
        "Año": "2024",
        "Mes": "Septiembre",
        "Ciudad": "Santiago",
        "Día": "Miércoles",
        "Institución Financiera": "Banco BICE",
        "Producto": "T. Crédito",
        "Marca de Tarjeta": "VISA",
        "Segmento": "Todos",
        "Local": "Olam",
        "Descuento": "40%",
        "Tope Descuento": "$50.000",
        "Observación": "",
        "Info": "https://banco.bice.cl/personas/beneficios/olam"
    },
    {
        "Año": "2024",
        "Mes": "Septiembre",
        "Ciudad": "Santiago",
        "Día": "Jueves",
        "Institución Financiera": "Banco BICE",
        "Producto": "T. Crédito",
        "Marca de Tarjeta": "VISA",
        "Segmento": "Todos",
        "Local": "Bar Alonso",
        "Descuento": "40%",
        "Tope Descuento": "$50.000",
        "Observación": "",
        "Info": "https://banco.bice.cl/personas/beneficios/bar-alonso"
    },
    {
        "Año": "2024",
        "Mes": "Septiembre",
        "Ciudad": "Santiago",
        "Día": "Viernes",
        "Institución Financiera": "Banco BICE",
        "Producto": "T. Crédito",
        "Marca de Tarjeta": "VISA",
        "Segmento": "Todos",
        "Local": "Mia Bar",
        "Descuento": "40%",
        "Tope Descuento": "$50.000",
        "Observación": "",
        "Info": "https://banco.bice.cl/personas/beneficios/mia-bar"
    },
    {
        "Año": "2024",
        "Mes": "Septiembre",
        "Ciudad": "Santiago",
        "Día": "Sábado",
        "Institución Financiera": "Banco BICE",
        "Producto": "T. Crédito",
        "Marca de Tarjeta": "VISA",
        "Segmento": "Signature",
        "Local": "Zanzibar",
        "Descuento": "50%",
        "Tope Descuento": "$80.000",
        "Observación": "",
        "Info": "https://banco.bice.cl/personas/beneficios/zanzibar"
    },
    {
        "Año": "2024",
        "Mes": "Septiembre",
        "Ciudad": "Santiago",
        "Día": "Domingo",
        "Institución Financiera": "Banco BICE",
        "Producto": "T. Crédito",
        "Marca de Tarjeta": "VISA",
        "Segmento": "Signature",
        "Local": "Kechua",
        "Descuento": "50%",
        "Tope Descuento": "$80.000",
        "Observación": "",
        "Info": "https://banco.bice.cl/personas/beneficios/kechua"
    },
    {
        "Año": "2024",
        "Mes": "Septiembre",
        "Ciudad": "Santiago",
        "Día": "Jueves",
        "Institución Financiera": "Banco BICE",
        "Producto": "T. Crédito",
        "Marca de Tarjeta": "VISA",
        "Segmento": "Banca Joven",
        "Local": "Bar Santiago",
        "Descuento": "40%",
        "Tope Descuento": "$30.000",
        "Observación": "",
        "Info": "https://banco.bice.cl/personas/beneficios/bar-santiago"
    },
    {
        "Año": "2024",
        "Mes": "Septiembre",
        "Ciudad": "Santiago",
        "Día": "Lunes",
        "Institución Financiera": "Banco Security",
        "Producto": "T. Crédito",
        "Marca de Tarjeta": "",
        "Segmento": "ONE",
        "Local": "La Panera Rosa",
        "Descuento": "40%",
        "Tope Descuento": "$50.000",
        "Observación": "",
        "Info": "https://personas.bancosecurity.cl/beneficios/gourmet/la-panera-rosa"
    },
    {
        "Año": "2024",
        "Mes": "Septiembre",
        "Ciudad": "Santiago",
        "Día": "Martes",
        "Institución Financiera": "Banco Security",
        "Producto": "T. Crédito",
        "Marca de Tarjeta": "",
        "Segmento": "ONE",
        "Local": "Cuerovaca",
        "Descuento": "40%",
        "Tope Descuento": "$50.000",
        "Observación": "",
        "Info": "https://personas.bancosecurity.cl/beneficios/gourmet/cuerovaca-0"
    },
    {
        "Año": "2024",
        "Mes": "Septiembre",
        "Ciudad": "Santiago",
        "Día": "Miércoles",
        "Institución Financiera": "Banco Security",
        "Producto": "T. Crédito",
        "Marca de Tarjeta": "",
        "Segmento": "ONE",
        "Local": "Naoki",
        "Descuento": "40%",
        "Tope Descuento": "$50.000",
        "Observación": "",
        "Info": "https://personas.bancosecurity.cl/beneficios/gourmet/naoki"
    },
    {
        "Año": "2024",
        "Mes": "Septiembre",
        "Ciudad": "Santiago",
        "Día": "Jueves",
        "Institución Financiera": "Banco Security",
        "Producto": "T. Crédito",
        "Marca de Tarjeta": "",
        "Segmento": "ONE",
        "Local": "Barrica 94",
        "Descuento": "50%",
        "Tope Descuento": "$50.000",
        "Observación": "",
        "Info": "https://personas.bancosecurity.cl/beneficios/gourmet/barrica-94"
    },
    {
        "Año": "2024",
        "Mes": "Septiembre",
        "Ciudad": "Santiago",
        "Día": "Viernes",
        "Institución Financiera": "Banco Security",
        "Producto": "T. Crédito",
        "Marca de Tarjeta": "",
        "Segmento": "ONE",
        "Local": "Nkiru",
        "Descuento": "30%",
        "Tope Descuento": "$50.000",
        "Observación": "",
        "Info": "https://personas.bancosecurity.cl/beneficios/gourmet/nkiru-bar"
    },
    {
        "Año": "2024",
        "Mes": "Septiembre",
        "Ciudad": "Santiago",
        "Día": "Sábado",
        "Institución Financiera": "Banco Security",
        "Producto": "T. Crédito",
        "Marca de Tarjeta": "",
        "Segmento": "ONE",
        "Local": "Gi Restaurant",
        "Descuento": "30%",
        "Tope Descuento": "$50.000",
        "Observación": "",
        "Info": "https://personas.bancosecurity.cl/beneficios/gourmet/gi-restaurant"
    },
    {
        "Año": "2024",
        "Mes": "Septiembre",
        "Ciudad": "Santiago",
        "Día": "Domingo",
        "Institución Financiera": "Banco Security",
        "Producto": "T. Crédito",
        "Marca de Tarjeta": "",
        "Segmento": "ONE",
        "Local": "Sicily Pizzeria",
        "Descuento": "30%",
        "Tope Descuento": "$50.000",
        "Observación": "",
        "Info": "https://personas.bancosecurity.cl/beneficios/gourmet/sicily-pizzeria"
    },
    {
        "Año": "2024",
        "Mes": "Septiembre",
        "Ciudad": "Santiago",
        "Día": "Lunes",
        "Institución Financiera": "Banco Itaú",
        "Producto": "T. Crédito",
        "Marca de Tarjeta": "Mastercard",
        "Segmento": "Black",
        "Local": "Ciro's",
        "Descuento": "40%",
        "Tope Descuento": "$50.000",
        "Observación": "",
        "Info": "https://itaubeneficios.cl/lunes-gourmet/ciros-bar/"
    },
    {
        "Año": "2024",
        "Mes": "Septiembre",
        "Ciudad": "Santiago",
        "Día": "Martes",
        "Institución Financiera": "Banco Itaú",
        "Producto": "T. Crédito",
        "Marca de Tarjeta": "Mastercard",
        "Segmento": "Black",
        "Local": "Infiltrados",
        "Descuento": "40%",
        "Tope Descuento": "$50.000",
        "Observación": "",
        "Info": "https://itaubeneficios.cl/canje-gourmet/infiltrados-2/"
    },
    {
        "Año": "2024",
        "Mes": "Septiembre",
        "Ciudad": "Santiago",
        "Día": "Martes",
        "Institución Financiera": "Banco Itaú",
        "Producto": "T. Crédito",
        "Marca de Tarjeta": "Mastercard",
        "Segmento": "Black",
        "Local": "Tanaka",
        "Descuento": "40%",
        "Tope Descuento": "$50.000",
        "Observación": "",
        "Info": "https://itaubeneficios.cl/martes-gourmet/tanaka/"
    },
    {
        "Año": "2024",
        "Mes": "Septiembre",
        "Ciudad": "Santiago",
        "Día": "Miércoles",
        "Institución Financiera": "Banco Itaú",
        "Producto": "T. Crédito",
        "Marca de Tarjeta": "Mastercard",
        "Segmento": "Black",
        "Local": "Fukai",
        "Descuento": "40%",
        "Tope Descuento": "$50.000",
        "Observación": "",
        "Info": "https://itaubeneficios.cl/miercoles-gourmet/fukai-2/"
    },
    {
        "Año": "2024",
        "Mes": "Septiembre",
        "Ciudad": "Santiago",
        "Día": "Jueves",
        "Institución Financiera": "Banco Itaú",
        "Producto": "T. Crédito",
        "Marca de Tarjeta": "Mastercard",
        "Segmento": "Black",
        "Local": "Casaluz",
        "Descuento": "40%",
        "Tope Descuento": "$50.000",
        "Observación": "",
        "Info": "https://itaubeneficios.cl/jueves-gourmet/casaluz-restaurant/"
    },
    {
        "Año": "2024",
        "Mes": "Septiembre",
        "Ciudad": "Santiago",
        "Día": "Jueves",
        "Institución Financiera": "Banco Itaú",
        "Producto": "T. Crédito",
        "Marca de Tarjeta": "Mastercard",
        "Segmento": "Black",
        "Local": "Hijo Del Sol",
        "Descuento": "40%",
        "Tope Descuento": "$50.000",
        "Observación": "",
        "Info": "https://itaubeneficios.cl/jueves-gourmet/hijo-del-sol-2/"
    },
    {
        "Año": "2024",
        "Mes": "Septiembre",
        "Ciudad": "Santiago",
        "Día": "Lunes",
        "Institución Financiera": "Banco BICE",
        "Producto": "T. Débito",
        "Marca de Tarjeta": "",
        "Segmento": "",
        "Local": "Ambrosía",
        "Descuento": "40%",
        "Tope Descuento": "$50.000",
        "Observación": "",
        "Info": "https://banco.bice.cl/personas/beneficios/ambrosia"
    },
    {
        "Año": "2024",
        "Mes": "Septiembre",
        "Ciudad": "Santiago",
        "Día": "Martes",
        "Institución Financiera": "Banco BICE",
        "Producto": "T. Débito",
        "Marca de Tarjeta": "",
        "Segmento": "",
        "Local": "El Establo",
        "Descuento": "40%",
        "Tope Descuento": "$50.000",
        "Observación": "",
        "Info": "https://banco.bice.cl/personas/beneficios/el-establo"
    },
    {
        "Año": "2024",
        "Mes": "Septiembre",
        "Ciudad": "Santiago",
        "Día": "Miércoles",
        "Institución Financiera": "Banco BICE",
        "Producto": "T. Débito",
        "Marca de Tarjeta": "",
        "Segmento": "",
        "Local": "Olam",
        "Descuento": "40%",
        "Tope Descuento": "$50.000",
        "Observación": "",
        "Info": "https://banco.bice.cl/personas/beneficios/olam"
    },
    {
        "Año": "2024",
        "Mes": "Septiembre",
        "Ciudad": "Santiago",
        "Día": "Jueves",
        "Institución Financiera": "Banco BICE",
        "Producto": "T. Débito",
        "Marca de Tarjeta": "",
        "Segmento": "",
        "Local": "Bar Alonso",
        "Descuento": "40%",
        "Tope Descuento": "$50.000",
        "Observación": "",
        "Info": "https://banco.bice.cl/personas/beneficios/bar-alonso"
    },
    {
        "Año": "2024",
        "Mes": "Septiembre",
        "Ciudad": "Santiago",
        "Día": "Viernes",
        "Institución Financiera": "Banco BICE",
        "Producto": "T. Débito",
        "Marca de Tarjeta": "",
        "Segmento": "",
        "Local": "Mia Bar",
        "Descuento": "40%",
        "Tope Descuento": "$50.000",
        "Observación": "",
        "Info": "https://banco.bice.cl/personas/beneficios/mia-bar"
    },
    {
        "Año": "2024",
        "Mes": "Septiembre",
        "Ciudad": "Santiago",
        "Día": "Sábado",
        "Institución Financiera": "Banco BICE",
        "Producto": "T. Crédito",
        "Marca de Tarjeta": "VISA",
        "Segmento": "Infinite",
        "Local": "Zanzibar",
        "Descuento": "50%",
        "Tope Descuento": "$80.000",
        "Observación": "",
        "Info": "https://banco.bice.cl/personas/beneficios/zanzibar"
    },
    {
        "Año": "2024",
        "Mes": "Septiembre",
        "Ciudad": "Santiago",
        "Día": "Domingo",
        "Institución Financiera": "Banco BICE",
        "Producto": "T. Crédito",
        "Marca de Tarjeta": "VISA",
        "Segmento": "Infinite",
        "Local": "Kechua",
        "Descuento": "50%",
        "Tope Descuento": "$80.000",
        "Observación": "",
        "Info": "https://banco.bice.cl/personas/beneficios/kechua"
    },
    {
        "Año": "2024",
        "Mes": "Septiembre",
        "Ciudad": "Santiago",
        "Día": "Martes",
        "Institución Financiera": "Banco Falabella",
        "Producto": "T. Crédito",
        "Marca de Tarjeta": "",
        "Segmento": "",
        "Local": "Bar De Rio (Borde Río)",
        "Descuento": "40%",
        "Tope Descuento": "",
        "Observación": "Sólo válido en Borde Río",
        "Info": "https://www.bancofalabella.cl/descuentos/detalle/martes-de-borderio"
    },
    {
        "Año": "2024",
        "Mes": "Septiembre",
        "Ciudad": "Santiago",
        "Día": "Martes",
        "Institución Financiera": "Banco Falabella",
        "Producto": "T. Crédito",
        "Marca de Tarjeta": "",
        "Segmento": "",
        "Local": "Bar Santiago (Borde Río)",
        "Descuento": "40%",
        "Tope Descuento": "",
        "Observación": "Sólo válido en Borde Río",
        "Info": "https://www.bancofalabella.cl/descuentos/detalle/martes-de-borderio"
    },
    {
        "Año": "2024",
        "Mes": "Septiembre",
        "Ciudad": "Santiago",
        "Día": "Martes",
        "Institución Financiera": "Banco Falabella",
        "Producto": "T. Crédito",
        "Marca de Tarjeta": "",
        "Segmento": "",
        "Local": "Bistró & Café (Borde Río)",
        "Descuento": "40%",
        "Tope Descuento": "",
        "Observación": "Sólo válido en Borde Río",
        "Info": "https://www.bancofalabella.cl/descuentos/detalle/martes-de-borderio"
    },
    {
        "Año": "2024",
        "Mes": "Septiembre",
        "Ciudad": "Santiago",
        "Día": "Martes",
        "Institución Financiera": "Banco Falabella",
        "Producto": "T. Crédito",
        "Marca de Tarjeta": "",
        "Segmento": "",
        "Local": "Kechua (Borde Río)",
        "Descuento": "40%",
        "Tope Descuento": "",
        "Observación": "Sólo válido en Borde Río",
        "Info": "https://www.bancofalabella.cl/descuentos/detalle/martes-de-borderio"
    },
    {
        "Año": "2024",
        "Mes": "Septiembre",
        "Ciudad": "Santiago",
        "Día": "Martes",
        "Institución Financiera": "Banco Falabella",
        "Producto": "T. Crédito",
        "Marca de Tarjeta": "",
        "Segmento": "",
        "Local": "Krossbar (Borde Río)",
        "Descuento": "40%",
        "Tope Descuento": "",
        "Observación": "Sólo válido en Borde Río",
        "Info": "https://www.bancofalabella.cl/descuentos/detalle/martes-de-borderio"
    },
    {
        "Año": "2024",
        "Mes": "Septiembre",
        "Ciudad": "Santiago",
        "Día": "Martes",
        "Institución Financiera": "Banco Falabella",
        "Producto": "T. Crédito",
        "Marca de Tarjeta": "",
        "Segmento": "",
        "Local": "La Tabla (Borde Río)",
        "Descuento": "40%",
        "Tope Descuento": "",
        "Observación": "Sólo válido en Borde Río",
        "Info": "https://www.bancofalabella.cl/descuentos/detalle/martes-de-borderio"
    },
    {
        "Año": "2024",
        "Mes": "Septiembre",
        "Ciudad": "Santiago",
        "Día": "Martes",
        "Institución Financiera": "Banco Falabella",
        "Producto": "T. Crédito",
        "Marca de Tarjeta": "",
        "Segmento": "",
        "Local": "Pulmay (Borde Río)",
        "Descuento": "40%",
        "Tope Descuento": "",
        "Observación": "Sólo válido en Borde Río",
        "Info": "https://www.bancofalabella.cl/descuentos/detalle/martes-de-borderio"
    },
    {
        "Año": "2024",
        "Mes": "Septiembre",
        "Ciudad": "Santiago",
        "Día": "Martes",
        "Institución Financiera": "Banco Falabella",
        "Producto": "T. Crédito",
        "Marca de Tarjeta": "",
        "Segmento": "",
        "Local": "Zanzibar (Borde Río)",
        "Descuento": "40%",
        "Tope Descuento": "",
        "Observación": "Sólo válido en Borde Río",
        "Info": "https://www.bancofalabella.cl/descuentos/detalle/martes-de-borderio"
    },
    {
        "Año": "2024",
        "Mes": "Septiembre",
        "Ciudad": "Santiago",
        "Día": "Lunes",
        "Institución Financiera": "Banco Falabella",
        "Producto": "T. Crédito",
        "Marca de Tarjeta": "",
        "Segmento": "",
        "Local": "Berlin Doner Kebab",
        "Descuento": "40%",
        "Tope Descuento": "",
        "Observación": "",
        "Info": "https://www.bancofalabella.cl/descuentos/detalle/berlin-doner-kebab"
    },
    {
        "Año": "2024",
        "Mes": "Septiembre",
        "Ciudad": "Santiago",
        "Día": "Miércoles",
        "Institución Financiera": "Banco Falabella",
        "Producto": "T. Crédito",
        "Marca de Tarjeta": "",
        "Segmento": "",
        "Local": "Nelí (Parque Arauco)",
        "Descuento": "40%",
        "Tope Descuento": "",
        "Observación": "Parque Arauco",
        "Info": "https://www.bancofalabella.cl/descuentos/detalle/miercoles-gourmet-cmr"
    },
    {
        "Año": "2024",
        "Mes": "Septiembre",
        "Ciudad": "Santiago",
        "Día": "Miércoles",
        "Institución Financiera": "Banco Falabella",
        "Producto": "T. Crédito",
        "Marca de Tarjeta": "",
        "Segmento": "",
        "Local": "Uncle Fletch",
        "Descuento": "40%",
        "Tope Descuento": "",
        "Observación": "",
        "Info": "https://www.bancofalabella.cl/descuentos/detalle/miercoles-gourmet-cmr"
    },
    {
        "Año": "2024",
        "Mes": "Septiembre",
        "Ciudad": "Santiago",
        "Día": "Viernes",
        "Institución Financiera": "Banco Falabella",
        "Producto": "T. Crédito",
        "Marca de Tarjeta": "",
        "Segmento": "",
        "Local": "Ково",
        "Descuento": "40%",
        "Tope Descuento": "",
        "Observación": "",
        "Info": "https://www.bancofalabella.cl/descuentos/detalle/kobosushi"
    },
    {
        "Año": "2024",
        "Mes": "Septiembre",
        "Ciudad": "Santiago",
        "Día": "Lunes, Miércoles",
        "Institución Financiera": "Banco Falabella",
        "Producto": "T. Crédito",
        "Marca de Tarjeta": "",
        "Segmento": "",
        "Local": "Danés",
        "Descuento": "40%",
        "Tope Descuento": "",
        "Observación": "",
        "Info": "https://www.bancofalabella.cl/descuentos/detalle/danes"
    },
    {
        "Año": "2024",
        "Mes": "Septiembre",
        "Ciudad": "Santiago",
        "Día": "Lunes, Miércoles",
        "Institución Financiera": "Banco Falabella",
        "Producto": "T. Crédito",
        "Marca de Tarjeta": "",
        "Segmento": "",
        "Local": "La Mestranza",
        "Descuento": "40%",
        "Tope Descuento": "",
        "Observación": "",
        "Info": "https://www.bancofalabella.cl/descuentos/detalle/la-maestranza"
    },
    {
        "Año": "2024",
        "Mes": "Septiembre",
        "Ciudad": "Santiago",
        "Día": "Lunes, Miércoles, Viernes, Sábado, Domingo",
        "Institución Financiera": "Banco Falabella",
        "Producto": "T. Crédito",
        "Marca de Tarjeta": "",
        "Segmento": "",
        "Local": "Vapiano",
        "Descuento": "40%",
        "Tope Descuento": "",
        "Observación": "",
        "Info": "https://www.bancofalabella.cl/descuentos/detalle/vapiano"
    },
    {
        "Año": "2024",
        "Mes": "Septiembre",
        "Ciudad": "Santiago",
        "Día": "Miércoles, Jueves, Viernes, Sábado",
        "Institución Financiera": "Banco Falabella",
        "Producto": "T. Crédito",
        "Marca de Tarjeta": "",
        "Segmento": "",
        "Local": "El Japonés (Open Kennedy)",
        "Descuento": "40%",
        "Tope Descuento": "",
        "Observación": "Sólo en Open Kennedy desde las 19:30 hrs",
        "Info": "https://www.bancofalabella.cl/descuentos/detalle/Santiago-open-gourmet"
    },
    {
        "Año": "2024",
        "Mes": "Septiembre",
        "Ciudad": "Santiago",
        "Día": "Miércoles, Jueves, Viernes, Sábado",
        "Institución Financiera": "Banco Falabella",
        "Producto": "T. Crédito",
        "Marca de Tarjeta": "",
        "Segmento": "",
        "Local": "La Piazza (Open Kennedy)",
        "Descuento": "40%",
        "Tope Descuento": "",
        "Observación": "Sólo en Open Kennedy desde las 19:30 hrs",
        "Info": "https://www.bancofalabella.cl/descuentos/detalle/Santiago-open-gourmet"
    },
    {
        "Año": "2024",
        "Mes": "Septiembre",
        "Ciudad": "Santiago",
        "Día": "Miércoles, Jueves, Viernes, Sábado",
        "Institución Financiera": "Banco Falabella",
        "Producto": "T. Crédito",
        "Marca de Tarjeta": "",
        "Segmento": "",
        "Local": "Siete Cortes (Open Kennedy)",
        "Descuento": "40%",
        "Tope Descuento": "",
        "Observación": "Sólo en Open Kennedy desde las 19:30 hrs",
        "Info": "https://www.bancofalabella.cl/descuentos/detalle/Santiago-open-gourmet"
    },
    {
        "Año": "2024",
        "Mes": "Septiembre",
        "Ciudad": "Santiago",
        "Día": "Miércoles, Jueves, Viernes, Sábado",
        "Institución Financiera": "Banco Falabella",
        "Producto": "T. Crédito",
        "Marca de Tarjeta": "",
        "Segmento": "",
        "Local": "Jalisco (Open Kennedy)",
        "Descuento": "40%",
        "Tope Descuento": "",
        "Observación": "Sólo en Open Kennedy desde las 19:30 hrs",
        "Info": "https://www.bancofalabella.cl/descuentos/detalle/Santiago-open-gourmet"
    },
    {
        "Año": "2024",
        "Mes": "Septiembre",
        "Ciudad": "Santiago",
        "Día": "Miércoles, Jueves, Viernes, Sábado",
        "Institución Financiera": "Banco Falabella",
        "Producto": "T. Crédito",
        "Marca de Tarjeta": "",
        "Segmento": "",
        "Local": "La Sanguchera del Barrio (Open Kennedy)",
        "Descuento": "40%",
        "Tope Descuento": "",
        "Observación": "Sólo en Open Kennedy desde las 19:30 hrs",
        "Info": "https://www.bancofalabella.cl/descuentos/detalle/Santiago-open-gourmet"
    },
    {
        "Año": "2024",
        "Mes": "Septiembre",
        "Ciudad": "Santiago",
        "Día": "Miércoles, Jueves, Viernes, Sábado",
        "Institución Financiera": "Banco Falabella",
        "Producto": "T. Crédito",
        "Marca de Tarjeta": "",
        "Segmento": "",
        "Local": "El Bodegón (Open Kennedy)",
        "Descuento": "40%",
        "Tope Descuento": "",
        "Observación": "Sólo en Open Kennedy desde las 19:30 hrs",
        "Info": "https://www.bancofalabella.cl/descuentos/detalle/Santiago-open-gourmet"
    },
    {
        "Año": "2024",
        "Mes": "Septiembre",
        "Ciudad": "Santiago",
        "Día": "Miércoles, Jueves, Viernes, Sábado",
        "Institución Financiera": "Banco Falabella",
        "Producto": "T. Crédito",
        "Marca de Tarjeta": "",
        "Segmento": "",
        "Local": "Mesón del Marinero (Open Kennedy)",
        "Descuento": "40%",
        "Tope Descuento": "",
        "Observación": "Sólo en Open Kennedy desde las 19:30 hrs",
        "Info": "https://www.bancofalabella.cl/descuentos/detalle/Santiago-open-gourmet"
    },
    {
        "Año": "2024",
        "Mes": "Septiembre",
        "Ciudad": "Santiago",
        "Día": "Sábado, Domingo",
        "Institución Financiera": "Banco Falabella",
        "Producto": "T. Crédito",
        "Marca de Tarjeta": "",
        "Segmento": "",
        "Local": "Cantina Isidora (Isidora Goy.)",
        "Descuento": "40%",
        "Tope Descuento": "",
        "Observación": "Sólo en Isidora Goyenechea",
        "Info": "https://www.bancofalabella.cl/descuentos/detalle/isidora-3000-jueves-viernes"
    },
    {
        "Año": "2024",
        "Mes": "Septiembre",
        "Ciudad": "Santiago",
        "Día": "Sábado, Domingo",
        "Institución Financiera": "Banco Falabella",
        "Producto": "T. Crédito",
        "Marca de Tarjeta": "",
        "Segmento": "",
        "Local": "Muu Steak (Isidora Goy.)",
        "Descuento": "40%",
        "Tope Descuento": "",
        "Observación": "Sólo en Isidora Goyenechea",
        "Info": "https://www.bancofalabella.cl/descuentos/detalle/isidora-3000-jueves-viernes"
    },
    {
        "Año": "2024",
        "Mes": "Septiembre",
        "Ciudad": "Santiago",
        "Día": "Sábado, Domingo",
        "Institución Financiera": "Banco Falabella",
        "Producto": "T. Crédito",
        "Marca de Tarjeta": "",
        "Segmento": "",
        "Local": "Tanta (Isidora Goy.)",
        "Descuento": "40%",
        "Tope Descuento": "",
        "Observación": "Sólo en Isidora Goyenechea",
        "Info": "https://www.bancofalabella.cl/descuentos/detalle/isidora-3000-jueves-viernes"
    },
    {
        "Año": "2024",
        "Mes": "Septiembre",
        "Ciudad": "Santiago",
        "Día": "Lunes, Martes, Miércoles, Jueves, Viernes",
        "Institución Financiera": "Banco Falabella",
        "Producto": "T. Crédito",
        "Marca de Tarjeta": "",
        "Segmento": "",
        "Local": "Selección Mall Plaza",
        "Descuento": "40%",
        "Tope Descuento": "",
        "Observación": "",
        "Info": "https://www.bancofalabella.cl/descuentos/detalle/40-de-dcto-en-restaurantes-mallplaza"
    },
    {
        "Año": "2024",
        "Mes": "Septiembre",
        "Ciudad": "Santiago",
        "Día": "Lunes",
        "Institución Financiera": "Banco Falabella",
        "Producto": "T. Crédito",
        "Marca de Tarjeta": "",
        "Segmento": "CMR Elite",
        "Local": "Naoki",
        "Descuento": "40%",
        "Tope Descuento": "",
        "Observación": "",
        "Info": "https://www.bancofalabella.cl/descuentos/detalle/40-naoki"
    },
    {
        "Año": "2024",
        "Mes": "Septiembre",
        "Ciudad": "Santiago",
        "Día": "Martes",
        "Institución Financiera": "Banco Falabella",
        "Producto": "T. Crédito",
        "Marca de Tarjeta": "",
        "Segmento": "CMR Elite",
        "Local": "Ceiba",
        "Descuento": "40%",
        "Tope Descuento": "",
        "Observación": "",
        "Info": "https://www.bancofalabella.cl/descuentos/detalle/40-ceiba"
    },
    {
        "Año": "2024",
        "Mes": "Septiembre",
        "Ciudad": "Santiago",
        "Día": "Jueves",
        "Institución Financiera": "Banco Falabella",
        "Producto": "T. Crédito",
        "Marca de Tarjeta": "",
        "Segmento": "CMR Elite",
        "Local": "La Dicha",
        "Descuento": "40%",
        "Tope Descuento": "",
        "Observación": "",
        "Info": "https://www.bancofalabella.cl/descuentos/detalle/la-dicha"
    },
    {
        "Año": "2024",
        "Mes": "Septiembre",
        "Ciudad": "Santiago",
        "Día": "Jueves",
        "Institución Financiera": "Banco Falabella",
        "Producto": "T. Crédito",
        "Marca de Tarjeta": "",
        "Segmento": "CMR Elite",
        "Local": "La Picanteria",
        "Descuento": "40%",
        "Tope Descuento": "",
        "Observación": "",
        "Info": "https://www.bancofalabella.cl/descuentos/detalle/40-la-picanteria"
    },
    {
        "Año": "2024",
        "Mes": "Septiembre",
        "Ciudad": "Santiago",
        "Día": "Viernes",
        "Institución Financiera": "Banco Falabella",
        "Producto": "T. Crédito",
        "Marca de Tarjeta": "",
        "Segmento": "CMR Elite",
        "Local": "Ciro's",
        "Descuento": "40%",
        "Tope Descuento": "",
        "Observación": "",
        "Info": "https://www.bancofalabella.cl/descuentos/detalle/ciros"
    },
    {
        "Año": "2024",
        "Mes": "Septiembre",
        "Ciudad": "Santiago",
        "Día": "Lunes",
        "Institución Financiera": "Scotiabank",
        "Producto": "T. Crédito",
        "Marca de Tarjeta": "VISA",
        "Segmento": "Signature, Infinite Wealth Management",
        "Local": "Carmine",
        "Descuento": "40%",
        "Tope Descuento": "",
        "Observación": "",
        "Info": "https://beneficios.scotiabank.cl/scclubfront/categoria/platosycomida/rutagourmet?_ga=2.263194315.6364236.1726322291-640661591.1726322291&_gl=1*iuxbe*_gcl_au*MTkzNTY2ODcuMTcyNjMyMjI5MQ..*_ga*NjQwNjYxNTkxLjE3MjYzMjIyOTE.*_ga_6EDD061F8G*MTcyNjM0NDM5Mi4zLjAuMTcyNjM0NDM5Mi4wLjAuMA.."
    },
    {
        "Año": "2024",
        "Mes": "Septiembre",
        "Ciudad": "Santiago",
        "Día": "Lunes",
        "Institución Financiera": "Scotiabank",
        "Producto": "T. Crédito",
        "Marca de Tarjeta": "VISA",
        "Segmento": "Signature, Infinite Wealth Management",
        "Local": "Sabor Y Aroma",
        "Descuento": "50%",
        "Tope Descuento": "",
        "Observación": "",
        "Info": "https://beneficios.scotiabank.cl/scclubfront/categoria/platosycomida/rutagourmet?_ga=2.263194315.6364236.1726322291-640661591.1726322291&_gl=1*iuxbe*_gcl_au*MTkzNTY2ODcuMTcyNjMyMjI5MQ..*_ga*NjQwNjYxNTkxLjE3MjYzMjIyOTE.*_ga_6EDD061F8G*MTcyNjM0NDM5Mi4zLjAuMTcyNjM0NDM5Mi4wLjAuMA.."
    },
    {
        "Año": "2024",
        "Mes": "Septiembre",
        "Ciudad": "Santiago",
        "Día": "Martes",
        "Institución Financiera": "Scotiabank",
        "Producto": "T. Crédito",
        "Marca de Tarjeta": "VISA",
        "Segmento": "Signature, Infinite Wealth Management",
        "Local": "El Meson De La Pat.",
        "Descuento": "50%",
        "Tope Descuento": "",
        "Observación": "",
        "Info": "https://beneficios.scotiabank.cl/scclubfront/categoria/platosycomida/rutagourmet?_ga=2.263194315.6364236.1726322291-640661591.1726322291&_gl=1*iuxbe*_gcl_au*MTkzNTY2ODcuMTcyNjMyMjI5MQ..*_ga*NjQwNjYxNTkxLjE3MjYzMjIyOTE.*_ga_6EDD061F8G*MTcyNjM0NDM5Mi4zLjAuMTcyNjM0NDM5Mi4wLjAuMA.."
    },
    {
        "Año": "2024",
        "Mes": "Septiembre",
        "Ciudad": "Santiago",
        "Día": "Martes",
        "Institución Financiera": "Scotiabank",
        "Producto": "T. Crédito",
        "Marca de Tarjeta": "VISA",
        "Segmento": "Signature, Infinite Wealth Management",
        "Local": "Piso Uno",
        "Descuento": "50%",
        "Tope Descuento": "",
        "Observación": "",
        "Info": "https://beneficios.scotiabank.cl/scclubfront/categoria/platosycomida/rutagourmet?_ga=2.263194315.6364236.1726322291-640661591.1726322291&_gl=1*iuxbe*_gcl_au*MTkzNTY2ODcuMTcyNjMyMjI5MQ..*_ga*NjQwNjYxNTkxLjE3MjYzMjIyOTE.*_ga_6EDD061F8G*MTcyNjM0NDM5Mi4zLjAuMTcyNjM0NDM5Mi4wLjAuMA.."
    },
    {
        "Año": "2024",
        "Mes": "Septiembre",
        "Ciudad": "Santiago",
        "Día": "Martes",
        "Institución Financiera": "Scotiabank",
        "Producto": "T. Crédito",
        "Marca de Tarjeta": "VISA",
        "Segmento": "Signature, Infinite Wealth Management",
        "Local": "Yma",
        "Descuento": "40%",
        "Tope Descuento": "",
        "Observación": "",
        "Info": "https://beneficios.scotiabank.cl/scclubfront/categoria/platosycomida/rutagourmet?_ga=2.263194315.6364236.1726322291-640661591.1726322291&_gl=1*iuxbe*_gcl_au*MTkzNTY2ODcuMTcyNjMyMjI5MQ..*_ga*NjQwNjYxNTkxLjE3MjYzMjIyOTE.*_ga_6EDD061F8G*MTcyNjM0NDM5Mi4zLjAuMTcyNjM0NDM5Mi4wLjAuMA.."
    },
    {
        "Año": "2024",
        "Mes": "Septiembre",
        "Ciudad": "Santiago",
        "Día": "Miércoles",
        "Institución Financiera": "Scotiabank",
        "Producto": "T. Crédito",
        "Marca de Tarjeta": "VISA",
        "Segmento": "Signature, Infinite Wealth Management",
        "Local": "Consenza",
        "Descuento": "40%",
        "Tope Descuento": "",
        "Observación": "",
        "Info": "https://beneficios.scotiabank.cl/scclubfront/categoria/platosycomida/rutagourmet?_ga=2.263194315.6364236.1726322291-640661591.1726322291&_gl=1*iuxbe*_gcl_au*MTkzNTY2ODcuMTcyNjMyMjI5MQ..*_ga*NjQwNjYxNTkxLjE3MjYzMjIyOTE.*_ga_6EDD061F8G*MTcyNjM0NDM5Mi4zLjAuMTcyNjM0NDM5Mi4wLjAuMA.."
    },
    {
        "Año": "2024",
        "Mes": "Septiembre",
        "Ciudad": "Santiago",
        "Día": "Miércoles",
        "Institución Financiera": "Scotiabank",
        "Producto": "T. Crédito",
        "Marca de Tarjeta": "VISA",
        "Segmento": "Signature, Infinite Wealth Management",
        "Local": "Taringa",
        "Descuento": "50%",
        "Tope Descuento": "",
        "Observación": "",
        "Info": "https://beneficios.scotiabank.cl/scclubfront/categoria/platosycomida/rutagourmet?_ga=2.263194315.6364236.1726322291-640661591.1726322291&_gl=1*iuxbe*_gcl_au*MTkzNTY2ODcuMTcyNjMyMjI5MQ..*_ga*NjQwNjYxNTkxLjE3MjYzMjIyOTE.*_ga_6EDD061F8G*MTcyNjM0NDM5Mi4zLjAuMTcyNjM0NDM5Mi4wLjAuMA.."
    },
    {
        "Año": "2024",
        "Mes": "Septiembre",
        "Ciudad": "Santiago",
        "Día": "Jueves",
        "Institución Financiera": "Scotiabank",
        "Producto": "T. Crédito",
        "Marca de Tarjeta": "VISA",
        "Segmento": "Signature, Infinite Wealth Management",
        "Local": "De Pura Madre",
        "Descuento": "40%",
        "Tope Descuento": "",
        "Observación": "",
        "Info": "https://beneficios.scotiabank.cl/scclubfront/categoria/platosycomida/rutagourmet?_ga=2.263194315.6364236.1726322291-640661591.1726322291&_gl=1*iuxbe*_gcl_au*MTkzNTY2ODcuMTcyNjMyMjI5MQ..*_ga*NjQwNjYxNTkxLjE3MjYzMjIyOTE.*_ga_6EDD061F8G*MTcyNjM0NDM5Mi4zLjAuMTcyNjM0NDM5Mi4wLjAuMA.."
    },
    {
        "Año": "2024",
        "Mes": "Septiembre",
        "Ciudad": "Santiago",
        "Día": "Jueves",
        "Institución Financiera": "Scotiabank",
        "Producto": "T. Crédito",
        "Marca de Tarjeta": "VISA",
        "Segmento": "Signature, Infinite Wealth Management",
        "Local": "Santa Brasa",
        "Descuento": "50%",
        "Tope Descuento": "",
        "Observación": "",
        "Info": "https://beneficios.scotiabank.cl/scclubfront/categoria/platosycomida/rutagourmet?_ga=2.263194315.6364236.1726322291-640661591.1726322291&_gl=1*iuxbe*_gcl_au*MTkzNTY2ODcuMTcyNjMyMjI5MQ..*_ga*NjQwNjYxNTkxLjE3MjYzMjIyOTE.*_ga_6EDD061F8G*MTcyNjM0NDM5Mi4zLjAuMTcyNjM0NDM5Mi4wLjAuMA.."
    },
    {
        "Año": "2024",
        "Mes": "Septiembre",
        "Ciudad": "Santiago",
        "Día": "Viernes",
        "Institución Financiera": "Scotiabank",
        "Producto": "T. Crédito",
        "Marca de Tarjeta": "VISA",
        "Segmento": "Signature, Infinite Wealth Management",
        "Local": "Estación 59",
        "Descuento": "50%",
        "Tope Descuento": "",
        "Observación": "",
        "Info": "https://beneficios.scotiabank.cl/scclubfront/categoria/platosycomida/rutagourmet?_ga=2.263194315.6364236.1726322291-640661591.1726322291&_gl=1*iuxbe*_gcl_au*MTkzNTY2ODcuMTcyNjMyMjI5MQ..*_ga*NjQwNjYxNTkxLjE3MjYzMjIyOTE.*_ga_6EDD061F8G*MTcyNjM0NDM5Mi4zLjAuMTcyNjM0NDM5Mi4wLjAuMA.."
    },
    {
        "Año": "2024",
        "Mes": "Septiembre",
        "Ciudad": "Santiago",
        "Día": "Viernes",
        "Institución Financiera": "Scotiabank",
        "Producto": "T. Crédito",
        "Marca de Tarjeta": "VISA",
        "Segmento": "Signature, Infinite Wealth Management",
        "Local": "Pomeriggio",
        "Descuento": "40%",
        "Tope Descuento": "",
        "Observación": "",
        "Info": "https://beneficios.scotiabank.cl/scclubfront/categoria/platosycomida/rutagourmet?_ga=2.263194315.6364236.1726322291-640661591.1726322291&_gl=1*iuxbe*_gcl_au*MTkzNTY2ODcuMTcyNjMyMjI5MQ..*_ga*NjQwNjYxNTkxLjE3MjYzMjIyOTE.*_ga_6EDD061F8G*MTcyNjM0NDM5Mi4zLjAuMTcyNjM0NDM5Mi4wLjAuMA.."
    },
    {
        "Año": "2024",
        "Mes": "Septiembre",
        "Ciudad": "Santiago",
        "Día": "Sábado",
        "Institución Financiera": "Scotiabank",
        "Producto": "T. Crédito",
        "Marca de Tarjeta": "VISA",
        "Segmento": "Signature, Infinite Wealth Management",
        "Local": "Karai",
        "Descuento": "50%",
        "Tope Descuento": "",
        "Observación": "",
        "Info": "https://beneficios.scotiabank.cl/scclubfront/categoria/platosycomida/rutagourmet?_ga=2.263194315.6364236.1726322291-640661591.1726322291&_gl=1*iuxbe*_gcl_au*MTkzNTY2ODcuMTcyNjMyMjI5MQ..*_ga*NjQwNjYxNTkxLjE3MjYzMjIyOTE.*_ga_6EDD061F8G*MTcyNjM0NDM5Mi4zLjAuMTcyNjM0NDM5Mi4wLjAuMA.."
    },
    {
        "Año": "2024",
        "Mes": "Septiembre",
        "Ciudad": "Santiago",
        "Día": "Sábado",
        "Institución Financiera": "Scotiabank",
        "Producto": "T. Crédito",
        "Marca de Tarjeta": "VISA",
        "Segmento": "Signature, Infinite Wealth Management",
        "Local": "Pasta Basta",
        "Descuento": "50%",
        "Tope Descuento": "",
        "Observación": "",
        "Info": "https://beneficios.scotiabank.cl/scclubfront/categoria/platosycomida/rutagourmet?_ga=2.263194315.6364236.1726322291-640661591.1726322291&_gl=1*iuxbe*_gcl_au*MTkzNTY2ODcuMTcyNjMyMjI5MQ..*_ga*NjQwNjYxNTkxLjE3MjYzMjIyOTE.*_ga_6EDD061F8G*MTcyNjM0NDM5Mi4zLjAuMTcyNjM0NDM5Mi4wLjAuMA.."
    },
    {
        "Año": "2024",
        "Mes": "Septiembre",
        "Ciudad": "Santiago",
        "Día": "Domingo",
        "Institución Financiera": "Scotiabank",
        "Producto": "T. Crédito",
        "Marca de Tarjeta": "VISA",
        "Segmento": "Signature, Infinite Wealth Management",
        "Local": "Rishtedar",
        "Descuento": "50%",
        "Tope Descuento": "",
        "Observación": "",
        "Info": "https://beneficios.scotiabank.cl/scclubfront/categoria/platosycomida/rutagourmet?_ga=2.263194315.6364236.1726322291-640661591.1726322291&_gl=1*iuxbe*_gcl_au*MTkzNTY2ODcuMTcyNjMyMjI5MQ..*_ga*NjQwNjYxNTkxLjE3MjYzMjIyOTE.*_ga_6EDD061F8G*MTcyNjM0NDM5Mi4zLjAuMTcyNjM0NDM5Mi4wLjAuMA.."
    },
    {
        "Año": "2024",
        "Mes": "Septiembre",
        "Ciudad": "Santiago",
        "Día": "Martes",
        "Institución Financiera": "Banco Falabella",
        "Producto": "T. Débito",
        "Marca de Tarjeta": "",
        "Segmento": "",
        "Local": "Bar De Rio (Borde Río)",
        "Descuento": "30%",
        "Tope Descuento": "",
        "Observación": "",
        "Info": "https://www.bancofalabella.cl/descuentos/detalle/martes-de-borderio"
    },
    {
        "Año": "2024",
        "Mes": "Septiembre",
        "Ciudad": "Santiago",
        "Día": "Martes",
        "Institución Financiera": "Banco Falabella",
        "Producto": "T. Débito",
        "Marca de Tarjeta": "",
        "Segmento": "",
        "Local": "Bar Santiago (Borde Río)",
        "Descuento": "30%",
        "Tope Descuento": "",
        "Observación": "",
        "Info": "https://www.bancofalabella.cl/descuentos/detalle/martes-de-borderio"
    },
    {
        "Año": "2024",
        "Mes": "Septiembre",
        "Ciudad": "Santiago",
        "Día": "Martes",
        "Institución Financiera": "Banco Falabella",
        "Producto": "T. Débito",
        "Marca de Tarjeta": "",
        "Segmento": "",
        "Local": "Bistró & Café (Borde Río)",
        "Descuento": "30%",
        "Tope Descuento": "",
        "Observación": "",
        "Info": "https://www.bancofalabella.cl/descuentos/detalle/martes-de-borderio"
    },
    {
        "Año": "2024",
        "Mes": "Septiembre",
        "Ciudad": "Santiago",
        "Día": "Martes",
        "Institución Financiera": "Banco Falabella",
        "Producto": "T. Débito",
        "Marca de Tarjeta": "",
        "Segmento": "",
        "Local": "Kechua (Borde Río)",
        "Descuento": "30%",
        "Tope Descuento": "",
        "Observación": "",
        "Info": "https://www.bancofalabella.cl/descuentos/detalle/martes-de-borderio"
    },
    {
        "Año": "2024",
        "Mes": "Septiembre",
        "Ciudad": "Santiago",
        "Día": "Martes",
        "Institución Financiera": "Banco Falabella",
        "Producto": "T. Débito",
        "Marca de Tarjeta": "",
        "Segmento": "",
        "Local": "Krossbar (Borde Río)",
        "Descuento": "30%",
        "Tope Descuento": "",
        "Observación": "",
        "Info": "https://www.bancofalabella.cl/descuentos/detalle/martes-de-borderio"
    },
    {
        "Año": "2024",
        "Mes": "Septiembre",
        "Ciudad": "Santiago",
        "Día": "Martes",
        "Institución Financiera": "Banco Falabella",
        "Producto": "T. Débito",
        "Marca de Tarjeta": "",
        "Segmento": "",
        "Local": "La Tabla (Borde Río)",
        "Descuento": "30%",
        "Tope Descuento": "",
        "Observación": "",
        "Info": "https://www.bancofalabella.cl/descuentos/detalle/martes-de-borderio"
    },
    {
        "Año": "2024",
        "Mes": "Septiembre",
        "Ciudad": "Santiago",
        "Día": "Martes",
        "Institución Financiera": "Banco Falabella",
        "Producto": "T. Débito",
        "Marca de Tarjeta": "",
        "Segmento": "",
        "Local": "Pulmay (Borde Río)",
        "Descuento": "30%",
        "Tope Descuento": "",
        "Observación": "",
        "Info": "https://www.bancofalabella.cl/descuentos/detalle/martes-de-borderio"
    },
    {
        "Año": "2024",
        "Mes": "Septiembre",
        "Ciudad": "Santiago",
        "Día": "Martes",
        "Institución Financiera": "Banco Falabella",
        "Producto": "T. Débito",
        "Marca de Tarjeta": "",
        "Segmento": "",
        "Local": "Zanzibar (Borde Río)",
        "Descuento": "30%",
        "Tope Descuento": "",
        "Observación": "",
        "Info": "https://www.bancofalabella.cl/descuentos/detalle/martes-de-borderio"
    },
    {
        "Año": "2024",
        "Mes": "Septiembre",
        "Ciudad": "Santiago",
        "Día": "Lunes",
        "Institución Financiera": "Banco Falabella",
        "Producto": "T. Débito",
        "Marca de Tarjeta": "",
        "Segmento": "",
        "Local": "Berlin Doner Kebab",
        "Descuento": "30%",
        "Tope Descuento": "",
        "Observación": "",
        "Info": "https://www.bancofalabella.cl/descuentos/detalle/berlin-doner-kebab"
    },
    {
        "Año": "2024",
        "Mes": "Septiembre",
        "Ciudad": "Santiago",
        "Día": "Miércoles",
        "Institución Financiera": "Banco Falabella",
        "Producto": "T. Débito",
        "Marca de Tarjeta": "",
        "Segmento": "",
        "Local": "Nelí (Parque Arauco)",
        "Descuento": "30%",
        "Tope Descuento": "",
        "Observación": "",
        "Info": "https://www.bancofalabella.cl/descuentos/detalle/miercoles-gourmet-cmr"
    },
    {
        "Año": "2024",
        "Mes": "Septiembre",
        "Ciudad": "Santiago",
        "Día": "Miércoles",
        "Institución Financiera": "Banco Falabella",
        "Producto": "T. Débito",
        "Marca de Tarjeta": "",
        "Segmento": "",
        "Local": "Uncle Fletch",
        "Descuento": "30%",
        "Tope Descuento": "",
        "Observación": "",
        "Info": "https://www.bancofalabella.cl/descuentos/detalle/miercoles-gourmet-cmr"
    },
    {
        "Año": "2024",
        "Mes": "Septiembre",
        "Ciudad": "Santiago",
        "Día": "Viernes",
        "Institución Financiera": "Banco Falabella",
        "Producto": "T. Débito",
        "Marca de Tarjeta": "",
        "Segmento": "",
        "Local": "Ково",
        "Descuento": "30%",
        "Tope Descuento": "",
        "Observación": "",
        "Info": "https://www.bancofalabella.cl/descuentos/detalle/kobosushi"
    },
    {
        "Año": "2024",
        "Mes": "Septiembre",
        "Ciudad": "Santiago",
        "Día": "Lunes, Miércoles",
        "Institución Financiera": "Banco Falabella",
        "Producto": "T. Débito",
        "Marca de Tarjeta": "",
        "Segmento": "",
        "Local": "Danés",
        "Descuento": "30%",
        "Tope Descuento": "",
        "Observación": "",
        "Info": "https://www.bancofalabella.cl/descuentos/detalle/danes"
    },
    {
        "Año": "2024",
        "Mes": "Septiembre",
        "Ciudad": "Santiago",
        "Día": "Lunes, Miércoles",
        "Institución Financiera": "Banco Falabella",
        "Producto": "T. Débito",
        "Marca de Tarjeta": "",
        "Segmento": "",
        "Local": "La Mestranza",
        "Descuento": "30%",
        "Tope Descuento": "",
        "Observación": "",
        "Info": "https://www.bancofalabella.cl/descuentos/detalle/la-maestranza"
    },
    {
        "Año": "2024",
        "Mes": "Septiembre",
        "Ciudad": "Santiago",
        "Día": "Lunes, Miércoles, Viernes, Sábado, Domingo",
        "Institución Financiera": "Banco Falabella",
        "Producto": "T. Débito",
        "Marca de Tarjeta": "",
        "Segmento": "",
        "Local": "Vapiano",
        "Descuento": "30%",
        "Tope Descuento": "",
        "Observación": "",
        "Info": "https://www.bancofalabella.cl/descuentos/detalle/vapiano"
    },
    {
        "Año": "2024",
        "Mes": "Septiembre",
        "Ciudad": "Santiago",
        "Día": "Miércoles, Jueves, Viernes, Sábado",
        "Institución Financiera": "Banco Falabella",
        "Producto": "T. Débito",
        "Marca de Tarjeta": "",
        "Segmento": "",
        "Local": "El Japonés",
        "Descuento": "30%",
        "Tope Descuento": "",
        "Observación": "",
        "Info": "https://www.bancofalabella.cl/descuentos/detalle/Santiago-open-gourmet"
    },
    {
        "Año": "2024",
        "Mes": "Septiembre",
        "Ciudad": "Santiago",
        "Día": "Miércoles, Jueves, Viernes, Sábado",
        "Institución Financiera": "Banco Falabella",
        "Producto": "T. Débito",
        "Marca de Tarjeta": "",
        "Segmento": "",
        "Local": "La Piazza",
        "Descuento": "30%",
        "Tope Descuento": "",
        "Observación": "",
        "Info": "https://www.bancofalabella.cl/descuentos/detalle/Santiago-open-gourmet"
    },
    {
        "Año": "2024",
        "Mes": "Septiembre",
        "Ciudad": "Santiago",
        "Día": "Miércoles, Jueves, Viernes, Sábado",
        "Institución Financiera": "Banco Falabella",
        "Producto": "T. Débito",
        "Marca de Tarjeta": "",
        "Segmento": "",
        "Local": "Siete Cortes",
        "Descuento": "30%",
        "Tope Descuento": "",
        "Observación": "",
        "Info": "https://www.bancofalabella.cl/descuentos/detalle/Santiago-open-gourmet"
    },
    {
        "Año": "2024",
        "Mes": "Septiembre",
        "Ciudad": "Santiago",
        "Día": "Miércoles, Jueves, Viernes, Sábado",
        "Institución Financiera": "Banco Falabella",
        "Producto": "T. Débito",
        "Marca de Tarjeta": "",
        "Segmento": "",
        "Local": "Jalisco",
        "Descuento": "30%",
        "Tope Descuento": "",
        "Observación": "",
        "Info": "https://www.bancofalabella.cl/descuentos/detalle/Santiago-open-gourmet"
    },
    {
        "Año": "2024",
        "Mes": "Septiembre",
        "Ciudad": "Santiago",
        "Día": "Miércoles, Jueves, Viernes, Sábado",
        "Institución Financiera": "Banco Falabella",
        "Producto": "T. Débito",
        "Marca de Tarjeta": "",
        "Segmento": "",
        "Local": "La Sanguchera del Barrio",
        "Descuento": "30%",
        "Tope Descuento": "",
        "Observación": "",
        "Info": "https://www.bancofalabella.cl/descuentos/detalle/Santiago-open-gourmet"
    },
    {
        "Año": "2024",
        "Mes": "Septiembre",
        "Ciudad": "Santiago",
        "Día": "Miércoles, Jueves, Viernes, Sábado",
        "Institución Financiera": "Banco Falabella",
        "Producto": "T. Débito",
        "Marca de Tarjeta": "",
        "Segmento": "",
        "Local": "El Bodegón",
        "Descuento": "30%",
        "Tope Descuento": "",
        "Observación": "",
        "Info": "https://www.bancofalabella.cl/descuentos/detalle/Santiago-open-gourmet"
    },
    {
        "Año": "2024",
        "Mes": "Septiembre",
        "Ciudad": "Santiago",
        "Día": "Miércoles, Jueves, Viernes, Sábado",
        "Institución Financiera": "Banco Falabella",
        "Producto": "T. Débito",
        "Marca de Tarjeta": "",
        "Segmento": "",
        "Local": "Mesón del Marinero",
        "Descuento": "30%",
        "Tope Descuento": "",
        "Observación": "",
        "Info": "https://www.bancofalabella.cl/descuentos/detalle/Santiago-open-gourmet"
    },
    {
        "Año": "2024",
        "Mes": "Septiembre",
        "Ciudad": "Santiago",
        "Día": "Sábado, Domingo",
        "Institución Financiera": "Banco Falabella",
        "Producto": "T. Débito",
        "Marca de Tarjeta": "",
        "Segmento": "",
        "Local": "Cantina Isidora",
        "Descuento": "30%",
        "Tope Descuento": "",
        "Observación": "",
        "Info": "https://www.bancofalabella.cl/descuentos/detalle/isidora-3000-jueves-viernes"
    },
    {
        "Año": "2024",
        "Mes": "Septiembre",
        "Ciudad": "Santiago",
        "Día": "Sábado, Domingo",
        "Institución Financiera": "Banco Falabella",
        "Producto": "T. Débito",
        "Marca de Tarjeta": "",
        "Segmento": "",
        "Local": "Muu Steak",
        "Descuento": "30%",
        "Tope Descuento": "",
        "Observación": "",
        "Info": "https://www.bancofalabella.cl/descuentos/detalle/isidora-3000-jueves-viernes"
    },
    {
        "Año": "2024",
        "Mes": "Septiembre",
        "Ciudad": "Santiago",
        "Día": "Sábado, Domingo",
        "Institución Financiera": "Banco Falabella",
        "Producto": "T. Débito",
        "Marca de Tarjeta": "",
        "Segmento": "",
        "Local": "Tanta",
        "Descuento": "30%",
        "Tope Descuento": "",
        "Observación": "",
        "Info": "https://www.bancofalabella.cl/descuentos/detalle/isidora-3000-jueves-viernes"
    },
    {
        "Año": "2024",
        "Mes": "Septiembre",
        "Ciudad": "Santiago",
        "Día": "Lunes, Martes, Miércoles, Jueves, Viernes",
        "Institución Financiera": "Banco Falabella",
        "Producto": "T. Débito",
        "Marca de Tarjeta": "",
        "Segmento": "",
        "Local": "Selección Mall Plaza",
        "Descuento": "30%",
        "Tope Descuento": "",
        "Observación": "",
        "Info": "https://www.bancofalabella.cl/descuentos/detalle/40-de-dcto-en-restaurantes-mallplaza"
    },
    {
        "Año": "2024",
        "Mes": "Septiembre",
        "Ciudad": "Santiago",
        "Día": "Lunes, Martes, Miércoles, Jueves",
        "Institución Financiera": "Copec Pay",
        "Producto": "T. Crédito",
        "Marca de Tarjeta": "Mastercard",
        "Segmento": "",
        "Local": "Streat Burger",
        "Descuento": "30%",
        "Tope Descuento": "",
        "Observación": "",
        "Info": "https://www.appcopec.cl/promo-y-beneficios/streat-burger/"
    },
    {
        "Año": "2024",
        "Mes": "Septiembre",
        "Ciudad": "Santiago",
        "Día": "Jueves, Viernes",
        "Institución Financiera": "Cencosud-Scotia",
        "Producto": "T. Crédito",
        "Marca de Tarjeta": "",
        "Segmento": "",
        "Local": "Cenco Mall Restaurantes",
        "Descuento": "40%",
        "Tope Descuento": "$50.000",
        "Observación": "Desde 19 hrs",
        "Info": "https://www.tarjetacencosud.cl/publico/beneficios/landing/cenco-malls"
    },
    {
        "Año": "2024",
        "Mes": "Septiembre",
        "Ciudad": "Santiago",
        "Día": "Jueves, Viernes",
        "Institución Financiera": "Cencosud-Scotia",
        "Producto": "T. Crédito",
        "Marca de Tarjeta": "",
        "Segmento": "",
        "Local": "Selección Mirador del Alto",
        "Descuento": "40%",
        "Tope Descuento": "$50.000",
        "Observación": "Desde 19 hrs",
        "Info": "https://www.tarjetacencosud.cl/publico/beneficios/landing/cenco-malls"
    },
    {
        "Año": "2024",
        "Mes": "Septiembre",
        "Ciudad": "Santiago",
        "Día": "Martes",
        "Institución Financiera": "Banco BCI",
        "Producto": "T. Crédito",
        "Marca de Tarjeta": "",
        "Segmento": "",
        "Local": "Chilis",
        "Descuento": "40%",
        "Tope Descuento": "$40.000",
        "Observación": "",
        "Info": "https://www.bci.cl/beneficios/beneficios/chilis-descuento"
    },
    {
        "Año": "2024",
        "Mes": "Septiembre",
        "Ciudad": "Santiago",
        "Día": "Martes",
        "Institución Financiera": "Banco BCI",
        "Producto": "T. Crédito",
        "Marca de Tarjeta": "",
        "Segmento": "",
        "Local": "PF Chang's",
        "Descuento": "40%",
        "Tope Descuento": "$40.000",
        "Observación": "",
        "Info": "https://www.bci.cl/beneficios/beneficios/pf-changs-descuento"
    },
    {
        "Año": "2024",
        "Mes": "Septiembre",
        "Ciudad": "Santiago",
        "Día": "Jueves",
        "Institución Financiera": "Banco BCI",
        "Producto": "T. Crédito",
        "Marca de Tarjeta": "",
        "Segmento": "",
        "Local": "Cocina de Javier",
        "Descuento": "40%",
        "Tope Descuento": "$40.000",
        "Observación": "",
        "Info": "https://www.bci.cl/beneficios/beneficios/descuento-la-cocina-de-javier"
    },
    {
        "Año": "2024",
        "Mes": "Septiembre",
        "Ciudad": "Santiago",
        "Día": "Jueves",
        "Institución Financiera": "Banco BCI",
        "Producto": "T. Crédito",
        "Marca de Tarjeta": "",
        "Segmento": "",
        "Local": "Galpon Alonso",
        "Descuento": "40%",
        "Tope Descuento": "$40.000",
        "Observación": "",
        "Info": "https://www.bci.cl/beneficios/beneficios/descuento-galpon-alonso-2"
    },
    {
        "Año": "2024",
        "Mes": "Septiembre",
        "Ciudad": "Santiago",
        "Día": "Jueves",
        "Institución Financiera": "Banco BCI",
        "Producto": "T. Crédito",
        "Marca de Tarjeta": "",
        "Segmento": "",
        "Local": "Latin Hotel Marriot",
        "Descuento": "50%",
        "Tope Descuento": "$40.000",
        "Observación": "",
        "Info": "https://www.bci.cl/beneficios/beneficios/latin-grill"
    },
    {
        "Año": "2024",
        "Mes": "Septiembre",
        "Ciudad": "Santiago",
        "Día": "Jueves",
        "Institución Financiera": "Banco BCI",
        "Producto": "T. Crédito",
        "Marca de Tarjeta": "",
        "Segmento": "",
        "Local": "Majka Bistró",
        "Descuento": "40%",
        "Tope Descuento": "$40.000",
        "Observación": "",
        "Info": "https://www.bci.cl/beneficios/beneficios/descuento-majka-bistro"
    },
    {
        "Año": "2024",
        "Mes": "Septiembre",
        "Ciudad": "Santiago",
        "Día": "Jueves",
        "Institución Financiera": "Banco BCI",
        "Producto": "T. Crédito",
        "Marca de Tarjeta": "",
        "Segmento": "",
        "Local": "Malva Loca",
        "Descuento": "40%",
        "Tope Descuento": "$40.000",
        "Observación": "",
        "Info": "https://www.bci.cl/beneficios/beneficios/descuento-malva-loca"
    },
    {
        "Año": "2024",
        "Mes": "Septiembre",
        "Ciudad": "Santiago",
        "Día": "Jueves",
        "Institución Financiera": "Banco BCI",
        "Producto": "T. Crédito",
        "Marca de Tarjeta": "",
        "Segmento": "",
        "Local": "Pomeriggio",
        "Descuento": "40%",
        "Tope Descuento": "$40.000",
        "Observación": "",
        "Info": "https://www.bci.cl/beneficios/beneficios/descuento-pomeriggio"
    },
    {
        "Año": "2024",
        "Mes": "Septiembre",
        "Ciudad": "Santiago",
        "Día": "Jueves",
        "Institución Financiera": "Banco BCI",
        "Producto": "T. Crédito",
        "Marca de Tarjeta": "",
        "Segmento": "",
        "Local": "Puerto Del Alto",
        "Descuento": "40%",
        "Tope Descuento": "$40.000",
        "Observación": "",
        "Info": "https://www.bci.cl/beneficios/beneficios/descuento-puerto-del-alto"
    },
    {
        "Año": "2024",
        "Mes": "Septiembre",
        "Ciudad": "Santiago",
        "Día": "Jueves",
        "Institución Financiera": "Banco BCI",
        "Producto": "T. Crédito",
        "Marca de Tarjeta": "",
        "Segmento": "",
        "Local": "Tomata Pizza",
        "Descuento": "40%",
        "Tope Descuento": "$40.000",
        "Observación": "",
        "Info": "https://www.bci.cl/beneficios/beneficios/descuento-tomata-pizza"
    },
    {
        "Año": "2024",
        "Mes": "Septiembre",
        "Ciudad": "Santiago",
        "Día": "Viernes",
        "Institución Financiera": "Banco BCI",
        "Producto": "T. Crédito",
        "Marca de Tarjeta": "",
        "Segmento": "",
        "Local": "Cuerovaca",
        "Descuento": "40%",
        "Tope Descuento": "$40.000",
        "Observación": "",
        "Info": "https://www.bci.cl/beneficios/beneficios/40percent-en-cuerovaca-los-viernes-de-vamos-2"
    },
    {
        "Año": "2024",
        "Mes": "Septiembre",
        "Ciudad": "Santiago",
        "Día": "Viernes",
        "Institución Financiera": "Banco BCI",
        "Producto": "T. Crédito",
        "Marca de Tarjeta": "",
        "Segmento": "",
        "Local": "Kantu",
        "Descuento": "40%",
        "Tope Descuento": "$40.000",
        "Observación": "",
        "Info": "https://www.bci.cl/beneficios/beneficios/descuento-kantu"
    },
    {
        "Año": "2024",
        "Mes": "Septiembre",
        "Ciudad": "Santiago",
        "Día": "Viernes",
        "Institución Financiera": "Banco BCI",
        "Producto": "T. Crédito",
        "Marca de Tarjeta": "",
        "Segmento": "",
        "Local": "La Biferia",
        "Descuento": "40%",
        "Tope Descuento": "$40.000",
        "Observación": "",
        "Info": "https://www.bci.cl/beneficios/beneficios/descuento-la-biferia-restaurant"
    },
    {
        "Año": "2024",
        "Mes": "Septiembre",
        "Ciudad": "Santiago",
        "Día": "Viernes",
        "Institución Financiera": "Banco BCI",
        "Producto": "T. Crédito",
        "Marca de Tarjeta": "",
        "Segmento": "",
        "Local": "La Picantería",
        "Descuento": "40%",
        "Tope Descuento": "$40.000",
        "Observación": "",
        "Info": "https://www.bci.cl/beneficios/beneficios/40percent-en-la-picanteria-los-viernes-de-vamos-2"
    },
    {
        "Año": "2024",
        "Mes": "Septiembre",
        "Ciudad": "Santiago",
        "Día": "Viernes",
        "Institución Financiera": "Banco BCI",
        "Producto": "T. Crédito",
        "Marca de Tarjeta": "",
        "Segmento": "",
        "Local": "Pescados Capitales",
        "Descuento": "40%",
        "Tope Descuento": "$40.000",
        "Observación": "",
        "Info": "https://www.bci.cl/beneficios/beneficios/40percent-de-dcto-en-pescados-capitales-los-viernes"
    },
    {
        "Año": "2024",
        "Mes": "Septiembre",
        "Ciudad": "Santiago",
        "Día": "Viernes",
        "Institución Financiera": "Banco BCI",
        "Producto": "T. Crédito",
        "Marca de Tarjeta": "",
        "Segmento": "",
        "Local": "Verde Sazón",
        "Descuento": "40%",
        "Tope Descuento": "$40.000",
        "Observación": "",
        "Info": "https://www.bci.cl/beneficios/beneficios/40percent-en-verde-sazon-los-viernes-de-vamos-2"
    },
    {
        "Año": "2024",
        "Mes": "Septiembre",
        "Ciudad": "Santiago",
        "Día": "Lunes, Martes",
        "Institución Financiera": "Banco BCI",
        "Producto": "T. Crédito",
        "Marca de Tarjeta": "",
        "Segmento": "BCI Plus Cashback",
        "Local": "Pizza Nostra",
        "Descuento": "40%",
        "Tope Descuento": "$40.000",
        "Observación": "Activar Cashback Bci",
        "Info": "https://www.bci.cl/beneficios/beneficios/la-pizza-nostra"
    },
    {
        "Año": "2024",
        "Mes": "Septiembre",
        "Ciudad": "Santiago",
        "Día": "Lunes, Miércoles, Viernes",
        "Institución Financiera": "Banco BCI",
        "Producto": "T. Crédito",
        "Marca de Tarjeta": "",
        "Segmento": "BCI Plus Cashback",
        "Local": "Cocina De Kaleta",
        "Descuento": "40%",
        "Tope Descuento": "$40.000",
        "Observación": "Activar Cashback Bci",
        "Info": "https://www.bci.cl/beneficios/beneficios/cashback-en-cocina-de-kaleta"
    },
    {
        "Año": "2024",
        "Mes": "Septiembre",
        "Ciudad": "Santiago",
        "Día": "Lunes, Miércoles, Viernes",
        "Institución Financiera": "Banco BCI",
        "Producto": "T. Crédito",
        "Marca de Tarjeta": "",
        "Segmento": "BCI Plus Cashback",
        "Local": "La Perla Del Pacífico",
        "Descuento": "40%",
        "Tope Descuento": "$40.000",
        "Observación": "Activar Cashback Bci",
        "Info": "https://www.bci.cl/beneficios/beneficios/cashback-en-la-perla-del-pacifico"
    },
    {
        "Año": "2024",
        "Mes": "Septiembre",
        "Ciudad": "Santiago",
        "Día": "Lunes, Miércoles, Viernes",
        "Institución Financiera": "Banco BCI",
        "Producto": "T. Crédito",
        "Marca de Tarjeta": "",
        "Segmento": "BCI Plus Cashback",
        "Local": "Trattoria Rita",
        "Descuento": "40%",
        "Tope Descuento": "$40.000",
        "Observación": "Activar Cashback Bci",
        "Info": "https://www.bci.cl/beneficios/beneficios/cashback-en-trattoria-rita"
    },
    {
        "Año": "2024",
        "Mes": "Septiembre",
        "Ciudad": "Santiago",
        "Día": "Martes, Miércoles, Jueves",
        "Institución Financiera": "Banco BCI",
        "Producto": "T. Crédito",
        "Marca de Tarjeta": "",
        "Segmento": "BCI Plus Cashback",
        "Local": "Kento Sushi",
        "Descuento": "40%",
        "Tope Descuento": "$40.000",
        "Observación": "Activar Cashback Bci",
        "Info": "https://www.bci.cl/beneficios/beneficios/cashback-en-kento-sushi"
    },
    {
        "Año": "2024",
        "Mes": "Septiembre",
        "Ciudad": "Santiago",
        "Día": "Miércoles, Sábado",
        "Institución Financiera": "Banco BCI",
        "Producto": "T. Crédito",
        "Marca de Tarjeta": "",
        "Segmento": "BCI Plus Cashback",
        "Local": "Expendio Montt",
        "Descuento": "40%",
        "Tope Descuento": "$40.000",
        "Observación": "Activar Cashback Bci",
        "Info": "https://www.bci.cl/beneficios/beneficios/cashback-en-bar-expendio"
    },
    {
        "Año": "2024",
        "Mes": "Septiembre",
        "Ciudad": "Santiago",
        "Día": "Miércoles, Sábado",
        "Institución Financiera": "Banco BCI",
        "Producto": "T. Crédito",
        "Marca de Tarjeta": "",
        "Segmento": "BCI Plus Cashback",
        "Local": "Porfirio",
        "Descuento": "40%",
        "Tope Descuento": "$40.000",
        "Observación": "Activar Cashback Bci",
        "Info": "https://www.bci.cl/beneficios/beneficios/cashback-en-bar-porfirio"
    },
    {
        "Año": "2024",
        "Mes": "Septiembre",
        "Ciudad": "Santiago",
        "Día": "Sábado, Domingo",
        "Institución Financiera": "Banco BCI",
        "Producto": "T. Crédito",
        "Marca de Tarjeta": "",
        "Segmento": "BCI Plus Cashback",
        "Local": "Caramagnola",
        "Descuento": "40%",
        "Tope Descuento": "$40.000",
        "Observación": "Activar Cashback Bci",
        "Info": "https://www.bci.cl/beneficios/beneficios/caramagnola-cashback"
    },
    {
        "Año": "2024",
        "Mes": "Septiembre",
        "Ciudad": "Santiago",
        "Día": "Viernes, Sábado, Domingo",
        "Institución Financiera": "Banco BCI",
        "Producto": "T. Crédito",
        "Marca de Tarjeta": "",
        "Segmento": "BCI Plus Cashback",
        "Local": "Baza Los Trapenses",
        "Descuento": "40%",
        "Tope Descuento": "$40.000",
        "Observación": "Activar Cashback Bci",
        "Info": "https://www.bci.cl/beneficios/beneficios/cashback-baza-vivo-los-trapenses"
    },
    {
        "Año": "2024",
        "Mes": "Septiembre",
        "Ciudad": "Santiago",
        "Día": "Lunes",
        "Institución Financiera": "Banco de Chile",
        "Producto": "T. Débito, T. Crédito",
        "Marca de Tarjeta": "VISA",
        "Segmento": "",
        "Local": "Al Pesto",
        "Descuento": "40%",
        "Tope Descuento": "$50.000",
        "Observación": "",
        "Info": "https://portales.bancochile.cl/personas/beneficios/sabores/40-de-descuento-visa/detalles/al-pesto-visa"
    },
    {
        "Año": "2024",
        "Mes": "Septiembre",
        "Ciudad": "Santiago",
        "Día": "Lunes",
        "Institución Financiera": "Banco de Chile",
        "Producto": "T. Débito, T. Crédito",
        "Marca de Tarjeta": "VISA",
        "Segmento": "",
        "Local": "Doña Paula",
        "Descuento": "40%",
        "Tope Descuento": "$50.000",
        "Observación": "",
        "Info": "https://portales.bancochile.cl/personas/beneficios/sabores/40-de-descuento-visa/detalles/dona-paula"
    },
    {
        "Año": "2024",
        "Mes": "Septiembre",
        "Ciudad": "Santiago",
        "Día": "Martes",
        "Institución Financiera": "Banco de Chile",
        "Producto": "T. Débito, T. Crédito",
        "Marca de Tarjeta": "VISA",
        "Segmento": "",
        "Local": "La Cocina De Javier",
        "Descuento": "30%",
        "Tope Descuento": "$50.000",
        "Observación": "",
        "Info": "https://portales.bancochile.cl/personas/beneficios/sabores/restaurantes-y-bares/detalles/la-cocina-de-javier"
    },
    {
        "Año": "2024",
        "Mes": "Septiembre",
        "Ciudad": "Santiago",
        "Día": "Martes",
        "Institución Financiera": "Banco de Chile",
        "Producto": "T. Débito, T. Crédito",
        "Marca de Tarjeta": "VISA",
        "Segmento": "",
        "Local": "La Perla Del Pacífico",
        "Descuento": "40%",
        "Tope Descuento": "$50.000",
        "Observación": "",
        "Info": "https://portales.bancochile.cl/personas/beneficios/sabores/40-de-descuento-visa/detalles/perla-del-pacifico-visa"
    },
    {
        "Año": "2024",
        "Mes": "Septiembre",
        "Ciudad": "Santiago",
        "Día": "Martes",
        "Institución Financiera": "Banco de Chile",
        "Producto": "T. Débito, T. Crédito",
        "Marca de Tarjeta": "VISA",
        "Segmento": "",
        "Local": "Quercus",
        "Descuento": "40%",
        "Tope Descuento": "$50.000",
        "Observación": "",
        "Info": "https://portales.bancochile.cl/personas/beneficios/sabores/40-de-descuento-visa/detalles/quercus-visa"
    },
    {
        "Año": "2024",
        "Mes": "Septiembre",
        "Ciudad": "Santiago",
        "Día": "Miércoles",
        "Institución Financiera": "Banco de Chile",
        "Producto": "T. Débito, T. Crédito",
        "Marca de Tarjeta": "VISA",
        "Segmento": "",
        "Local": "Capogrossi",
        "Descuento": "40%",
        "Tope Descuento": "$50.000",
        "Observación": "",
        "Info": "https://portales.bancochile.cl/personas/beneficios/sabores/40-de-descuento-visa/detalles/capogrossi-visa"
    },
    {
        "Año": "2024",
        "Mes": "Septiembre",
        "Ciudad": "Santiago",
        "Día": "Jueves",
        "Institución Financiera": "Banco de Chile",
        "Producto": "T. Débito, T. Crédito",
        "Marca de Tarjeta": "VISA",
        "Segmento": "",
        "Local": "Brasas Del Arriero",
        "Descuento": "40%",
        "Tope Descuento": "$50.000",
        "Observación": "",
        "Info": "https://portales.bancochile.cl/personas/beneficios/sabores/40-de-descuento-visa/detalles/brasas-arriero-40-dcto"
    },
    {
        "Año": "2024",
        "Mes": "Septiembre",
        "Ciudad": "Santiago",
        "Día": "Viernes",
        "Institución Financiera": "Banco de Chile",
        "Producto": "T. Débito, T. Crédito",
        "Marca de Tarjeta": "VISA",
        "Segmento": "",
        "Local": "Medanoso",
        "Descuento": "40%",
        "Tope Descuento": "$50.000",
        "Observación": "",
        "Info": "https://portales.bancochile.cl/personas/beneficios/sabores/40-de-descuento-visa/detalles/bar-medanoso-visa"
    },
    {
        "Año": "2024",
        "Mes": "Septiembre",
        "Ciudad": "Santiago",
        "Día": "Sábado",
        "Institución Financiera": "Banco de Chile",
        "Producto": "T. Débito, T. Crédito",
        "Marca de Tarjeta": "VISA",
        "Segmento": "",
        "Local": "Fechoría",
        "Descuento": "40%",
        "Tope Descuento": "$50.000",
        "Observación": "",
        "Info": "https://portales.bancochile.cl/personas/beneficios/sabores/40-de-descuento-visa/detalles/fechoria-restaurante-visa"
    },
    {
        "Año": "2024",
        "Mes": "Septiembre",
        "Ciudad": "Santiago",
        "Día": "Domingo",
        "Institución Financiera": "Banco de Chile",
        "Producto": "T. Débito, T. Crédito",
        "Marca de Tarjeta": "VISA",
        "Segmento": "",
        "Local": "La Calma De Rita",
        "Descuento": "40%",
        "Tope Descuento": "$50.000",
        "Observación": "",
        "Info": "https://portales.bancochile.cl/personas/beneficios/sabores/40-de-descuento-visa/detalles/calma-de-rita-40-dcto"
    },
    {
        "Año": "2024",
        "Mes": "Septiembre",
        "Ciudad": "Santiago",
        "Día": "Martes",
        "Institución Financiera": "Banco Ripley",
        "Producto": "T. Crédito",
        "Marca de Tarjeta": "",
        "Segmento": "",
        "Local": "Cantina Montt",
        "Descuento": "40%",
        "Tope Descuento": "$40.000",
        "Observación": "",
        "Info": "https://www.bancoripley.cl/beneficio?name=CantinaMontt&id=restofans_63d57ffe-19c8-4804-b8b2-708487987b75&fromSP=true"
    },
    {
        "Año": "2024",
        "Mes": "Septiembre",
        "Ciudad": "Santiago",
        "Día": "Miércoles",
        "Institución Financiera": "Banco Ripley",
        "Producto": "T. Crédito",
        "Marca de Tarjeta": "",
        "Segmento": "",
        "Local": "Nkiru",
        "Descuento": "40%",
        "Tope Descuento": "$40.000",
        "Observación": "",
        "Info": "https://www.bancoripley.cl/beneficio?name=NkiruBar&id=restofans_ccf73ad1-6842-4214-8974-688d281b1737&fromSP=true"
    },
    {
        "Año": "2024",
        "Mes": "Septiembre",
        "Ciudad": "Santiago",
        "Día": "Jueves",
        "Institución Financiera": "Banco Ripley",
        "Producto": "T. Crédito",
        "Marca de Tarjeta": "",
        "Segmento": "",
        "Local": "Fukai",
        "Descuento": "40%",
        "Tope Descuento": "$40.000",
        "Observación": "",
        "Info": "https://www.bancoripley.cl/beneficio?name=Fukai&id=restofans_a17569de-c15a-4780-9461-4139a9a9204b&fromSP=true"
    },
    {
        "Año": "2024",
        "Mes": "Septiembre",
        "Ciudad": "Santiago",
        "Día": "Jueves",
        "Institución Financiera": "Banco Ripley",
        "Producto": "T. Crédito",
        "Marca de Tarjeta": "",
        "Segmento": "",
        "Local": "Galpón Italia",
        "Descuento": "40%",
        "Tope Descuento": "$40.000",
        "Observación": "",
        "Info": "https://www.bancoripley.cl/beneficio?name=GalponItalia&id=restofans_d802e15a-188a-4fee-a1bc-697330b97da7&fromSP=true"
    },
    {
        "Año": "2024",
        "Mes": "Septiembre",
        "Ciudad": "Santiago",
        "Día": "Viernes",
        "Institución Financiera": "Banco Ripley",
        "Producto": "T. Crédito",
        "Marca de Tarjeta": "",
        "Segmento": "",
        "Local": "Castillo Hamburgo",
        "Descuento": "40%",
        "Tope Descuento": "$40.000",
        "Observación": "",
        "Info": "https://www.bancoripley.cl/beneficio?name=CastilloHamburgo&id=restofans_e9018e20-e8d1-4321-bcaa-019b48908080&fromSP=true"
    },
    {
        "Año": "2024",
        "Mes": "Septiembre",
        "Ciudad": "Santiago",
        "Día": "Sábado",
        "Institución Financiera": "Banco Ripley",
        "Producto": "T. Crédito",
        "Marca de Tarjeta": "",
        "Segmento": "",
        "Local": "Majestic",
        "Descuento": "40%",
        "Tope Descuento": "$40.000",
        "Observación": "",
        "Info": "https://www.bancoripley.cl/beneficio?name=Majestic&id=restofans_85774721-ee8e-4ccc-b548-1054b0d8d2cd&fromSP=true"
    },
    {
        "Año": "2024",
        "Mes": "Septiembre",
        "Ciudad": "Santiago",
        "Día": "Jueves, Viernes, Sábado",
        "Institución Financiera": "Tenpo",
        "Producto": "T. Crédito",
        "Marca de Tarjeta": "Mastecard",
        "Segmento": "",
        "Local": "Vicenzo",
        "Descuento": "30%",
        "Tope Descuento": "$100.000",
        "Observación": "",
        "Info": "https://www.tenpo.cl/beneficios/vicenzo-restaurant"
    },
    {
        "Año": "2024",
        "Mes": "Septiembre",
        "Ciudad": "Santiago",
        "Día": "Lunes, Martes",
        "Institución Financiera": "Tenpo",
        "Producto": "T. Crédito",
        "Marca de Tarjeta": "Mastecard",
        "Segmento": "",
        "Local": "Barbazul",
        "Descuento": "30%",
        "Tope Descuento": "$100.000",
        "Observación": "",
        "Info": "https://www.tenpo.cl/beneficios/barbazul"
    }
];
