import type { Descuento } from "./beneficios";

export function obtenerDescuentos(): Descuento[] {
    const descuentos: Descuento[] = [];

    const meses: string[] = [
        "enero",
        "febrero",
        "marzo",
        "abril",
        "mayo",
        "junio",
        "julio",
        "agosto",
        "septiembre",
        "octubre",
        "noviembre",
        "diciembre",
    ];

    try {
        for (const fila of filas) {
            const descuento = Number(
                fila["Descuento"]
                    .replaceAll("$", "")
                    .replaceAll(".", "")
                    .replaceAll("%", "")
                    .replaceAll(" ", "")
            );

            const ordenMes = meses.indexOf(fila["Mes"]) + 1;
            const productos = fila["Producto"].replaceAll(", ", ",").split(",");
            const dias = fila["Día"].replaceAll(", ", ",").split(",");

            for (const producto of productos) {
                for (const dia of dias) {
                    descuentos.push({
                        ano: Number(fila["Año"]),
                        ciudad: fila["Ciudad"],
                        descuento: descuento,
                        dia: dia,
                        mes: fila["Mes"],
                        ordenMes: ordenMes,
                        producto: producto,
                        proveedor: fila["Institución Financiera"],
                        tienda: fila["Local"],
                    });
                }
            }
        }
    } catch (error) {
        console.error("error al obtener descuentos", error);
    }

    return descuentos;
}

const filas = [
    {
        "Año": "2024",
        "Mes": "Septiembre",
        "Ciudad": "Santiago",
        "Día": "Miércoles",
        "Institución Financiera": "Banco Santander",
        "Producto": "T. Crédito",
        "Marca de Tarjeta": "",
        "Segmento": "",
        "Local": "Casa Morera",
        "Descuento": "40%",
        "Tope Descuento": "$40.000",
        "Observación": "",
        "Info": ""
    },
    {
        "Año": "2024",
        "Mes": "Septiembre",
        "Ciudad": "Santiago",
        "Día": "Miércoles",
        "Institución Financiera": "Banco Santander",
        "Producto": "T. Crédito",
        "Marca de Tarjeta": "",
        "Segmento": "",
        "Local": "Do Suhi",
        "Descuento": "40%",
        "Tope Descuento": "$40.000",
        "Observación": "",
        "Info": ""
    },
    {
        "Año": "2024",
        "Mes": "Septiembre",
        "Ciudad": "Santiago",
        "Día": "Miércoles",
        "Institución Financiera": "Banco Santander",
        "Producto": "T. Crédito",
        "Marca de Tarjeta": "",
        "Segmento": "",
        "Local": "Huo Del Sol",
        "Descuento": "40%",
        "Tope Descuento": "$40.000",
        "Observación": "",
        "Info": ""
    },
    {
        "Año": "2024",
        "Mes": "Septiembre",
        "Ciudad": "Santiago",
        "Día": "Miércoles",
        "Institución Financiera": "Banco Santander",
        "Producto": "T. Crédito",
        "Marca de Tarjeta": "",
        "Segmento": "",
        "Local": "La Burguesía",
        "Descuento": "40%",
        "Tope Descuento": "$40.000",
        "Observación": "",
        "Info": ""
    },
    {
        "Año": "2024",
        "Mes": "Septiembre",
        "Ciudad": "Santiago",
        "Día": "Miércoles",
        "Institución Financiera": "Banco Santander",
        "Producto": "T. Crédito",
        "Marca de Tarjeta": "",
        "Segmento": "",
        "Local": "La Cocina De Javier",
        "Descuento": "40%",
        "Tope Descuento": "$40.000",
        "Observación": "",
        "Info": ""
    },
    {
        "Año": "2024",
        "Mes": "Septiembre",
        "Ciudad": "Santiago",
        "Día": "Miércoles",
        "Institución Financiera": "Banco Santander",
        "Producto": "T. Crédito",
        "Marca de Tarjeta": "",
        "Segmento": "",
        "Local": "Local Burger",
        "Descuento": "40%",
        "Tope Descuento": "$40.000",
        "Observación": "",
        "Info": ""
    },
    {
        "Año": "2024",
        "Mes": "Septiembre",
        "Ciudad": "Santiago",
        "Día": "Miércoles",
        "Institución Financiera": "Banco Santander",
        "Producto": "T. Crédito",
        "Marca de Tarjeta": "",
        "Segmento": "",
        "Local": "Pf Chang'S",
        "Descuento": "40%",
        "Tope Descuento": "$40.000",
        "Observación": "",
        "Info": ""
    },
    {
        "Año": "2024",
        "Mes": "Septiembre",
        "Ciudad": "Santiago",
        "Día": "Miércoles",
        "Institución Financiera": "Banco Santander",
        "Producto": "T. Crédito",
        "Marca de Tarjeta": "",
        "Segmento": "",
        "Local": "Prima Bar",
        "Descuento": "40%",
        "Tope Descuento": "$40.000",
        "Observación": "",
        "Info": ""
    },
    {
        "Año": "2024",
        "Mes": "Septiembre",
        "Ciudad": "Santiago",
        "Día": "Miércoles",
        "Institución Financiera": "Banco Santander",
        "Producto": "T. Crédito",
        "Marca de Tarjeta": "",
        "Segmento": "",
        "Local": "Santa Brasa",
        "Descuento": "40%",
        "Tope Descuento": "$40.000",
        "Observación": "",
        "Info": ""
    },
    {
        "Año": "2024",
        "Mes": "Septiembre",
        "Ciudad": "Santiago",
        "Día": "Miércoles",
        "Institución Financiera": "Banco Santander",
        "Producto": "T. Crédito",
        "Marca de Tarjeta": "",
        "Segmento": "",
        "Local": "Soul Of India",
        "Descuento": "40%",
        "Tope Descuento": "$40.000",
        "Observación": "",
        "Info": ""
    },
    {
        "Año": "2024",
        "Mes": "Septiembre",
        "Ciudad": "Santiago",
        "Día": "Viernes",
        "Institución Financiera": "Banco Santander",
        "Producto": "T. Crédito",
        "Marca de Tarjeta": "",
        "Segmento": "",
        "Local": "Sakura*",
        "Descuento": "40%",
        "Tope Descuento": "$40.000",
        "Observación": "* Solo en Rolls y Hosomaki",
        "Info": ""
    },
    {
        "Año": "2024",
        "Mes": "Septiembre",
        "Ciudad": "Santiago",
        "Día": "Viernes",
        "Institución Financiera": "Banco Santander",
        "Producto": "T. Débito",
        "Marca de Tarjeta": "",
        "Segmento": "",
        "Local": "Sakura*",
        "Descuento": "40%",
        "Tope Descuento": "$40.000",
        "Observación": "* Solo en Rolls y Hosomaki",
        "Info": ""
    },
    {
        "Año": "2024",
        "Mes": "Septiembre",
        "Ciudad": "Santiago",
        "Día": "Lunes",
        "Institución Financiera": "Banco Santander",
        "Producto": "T. Crédito",
        "Marca de Tarjeta": "VISA - AMEX",
        "Segmento": "WorldMember Limited",
        "Local": "La Dicha",
        "Descuento": "40%",
        "Tope Descuento": "$100.000",
        "Observación": "",
        "Info": ""
    },
    {
        "Año": "2024",
        "Mes": "Septiembre",
        "Ciudad": "Santiago",
        "Día": "Martes",
        "Institución Financiera": "Banco Santander",
        "Producto": "T. Crédito",
        "Marca de Tarjeta": "VISA - AMEX",
        "Segmento": "WorldMember Limited",
        "Local": "Tomata",
        "Descuento": "40%",
        "Tope Descuento": "$100.000",
        "Observación": "",
        "Info": ""
    },
    {
        "Año": "2024",
        "Mes": "Septiembre",
        "Ciudad": "Santiago",
        "Día": "Miércoles",
        "Institución Financiera": "Banco Santander",
        "Producto": "T. Crédito",
        "Marca de Tarjeta": "VISA - AMEX",
        "Segmento": "WorldMember Limited",
        "Local": "La Picantería",
        "Descuento": "40%",
        "Tope Descuento": "$100.000",
        "Observación": "",
        "Info": ""
    },
    {
        "Año": "2024",
        "Mes": "Septiembre",
        "Ciudad": "Santiago",
        "Día": "Miércoles",
        "Institución Financiera": "Banco Santander",
        "Producto": "T. Crédito",
        "Marca de Tarjeta": "VISA - AMEX",
        "Segmento": "WorldMember Limited",
        "Local": "Piegari",
        "Descuento": "40%",
        "Tope Descuento": "$100.000",
        "Observación": "",
        "Info": ""
    },
    {
        "Año": "2024",
        "Mes": "Septiembre",
        "Ciudad": "Santiago",
        "Día": "Jueves",
        "Institución Financiera": "Banco Santander",
        "Producto": "T. Crédito",
        "Marca de Tarjeta": "VISA - AMEX",
        "Segmento": "WorldMember Limited",
        "Local": "Pescados Capitales",
        "Descuento": "40%",
        "Tope Descuento": "$100.000",
        "Observación": "",
        "Info": ""
    },
    {
        "Año": "2024",
        "Mes": "Septiembre",
        "Ciudad": "Santiago",
        "Día": "Lunes",
        "Institución Financiera": "Banco Santander",
        "Producto": "T. Crédito",
        "Marca de Tarjeta": "AMEX",
        "Segmento": "",
        "Local": "Carnal",
        "Descuento": "50%",
        "Tope Descuento": "$50.000",
        "Observación": "",
        "Info": ""
    },
    {
        "Año": "2024",
        "Mes": "Septiembre",
        "Ciudad": "Santiago",
        "Día": "Martes",
        "Institución Financiera": "Banco Santander",
        "Producto": "T. Crédito",
        "Marca de Tarjeta": "AMEX",
        "Segmento": "",
        "Local": "Jardín Mallinkrodt",
        "Descuento": "50%",
        "Tope Descuento": "$50.000",
        "Observación": "",
        "Info": ""
    },
    {
        "Año": "2024",
        "Mes": "Septiembre",
        "Ciudad": "Santiago",
        "Día": "Miércoles",
        "Institución Financiera": "Banco Santander",
        "Producto": "T. Crédito",
        "Marca de Tarjeta": "AMEX",
        "Segmento": "",
        "Local": "Bar 99",
        "Descuento": "50%",
        "Tope Descuento": "$50.000",
        "Observación": "",
        "Info": ""
    },
    {
        "Año": "2024",
        "Mes": "Septiembre",
        "Ciudad": "Santiago",
        "Día": "Jueves",
        "Institución Financiera": "Banco Santander",
        "Producto": "T. Crédito",
        "Marca de Tarjeta": "AMEX",
        "Segmento": "",
        "Local": "Yma",
        "Descuento": "50%",
        "Tope Descuento": "$50.000",
        "Observación": "",
        "Info": ""
    },
    {
        "Año": "2024",
        "Mes": "Septiembre",
        "Ciudad": "Santiago",
        "Día": "Viernes",
        "Institución Financiera": "Banco Santander",
        "Producto": "T. Crédito",
        "Marca de Tarjeta": "AMEX",
        "Segmento": "",
        "Local": "Otaki",
        "Descuento": "50%",
        "Tope Descuento": "$50.000",
        "Observación": "",
        "Info": ""
    },
    {
        "Año": "2024",
        "Mes": "Septiembre",
        "Ciudad": "Santiago",
        "Día": "Sábado",
        "Institución Financiera": "Banco Santander",
        "Producto": "T. Crédito",
        "Marca de Tarjeta": "AMEX",
        "Segmento": "",
        "Local": "Sabor Y Aroma",
        "Descuento": "50%",
        "Tope Descuento": "$50.000",
        "Observación": "",
        "Info": ""
    },
    {
        "Año": "2024",
        "Mes": "Septiembre",
        "Ciudad": "Santiago",
        "Día": "Domingo",
        "Institución Financiera": "Banco Santander",
        "Producto": "T. Crédito",
        "Marca de Tarjeta": "AMEX",
        "Segmento": "",
        "Local": "Gl",
        "Descuento": "50%",
        "Tope Descuento": "$50.000",
        "Observación": "",
        "Info": ""
    },
    {
        "Año": "2024",
        "Mes": "Septiembre",
        "Ciudad": "Santiago",
        "Día": "Lunes",
        "Institución Financiera": "Banco BICE",
        "Producto": "T. Crédito",
        "Marca de Tarjeta": "VISA",
        "Segmento": "",
        "Local": "Ambrosía",
        "Descuento": "40%",
        "Tope Descuento": "$50.000",
        "Observación": "",
        "Info": ""
    },
    {
        "Año": "2024",
        "Mes": "Septiembre",
        "Ciudad": "Santiago",
        "Día": "Martes",
        "Institución Financiera": "Banco BICE",
        "Producto": "T. Crédito",
        "Marca de Tarjeta": "VISA",
        "Segmento": "",
        "Local": "El Establo",
        "Descuento": "40%",
        "Tope Descuento": "$50.000",
        "Observación": "",
        "Info": ""
    },
    {
        "Año": "2024",
        "Mes": "Septiembre",
        "Ciudad": "Santiago",
        "Día": "Miércoles",
        "Institución Financiera": "Banco BICE",
        "Producto": "T. Crédito",
        "Marca de Tarjeta": "VISA",
        "Segmento": "",
        "Local": "Olam",
        "Descuento": "40%",
        "Tope Descuento": "$50.000",
        "Observación": "",
        "Info": ""
    },
    {
        "Año": "2024",
        "Mes": "Septiembre",
        "Ciudad": "Santiago",
        "Día": "Jueves",
        "Institución Financiera": "Banco BICE",
        "Producto": "T. Crédito",
        "Marca de Tarjeta": "VISA",
        "Segmento": "",
        "Local": "Bar Alonso",
        "Descuento": "40%",
        "Tope Descuento": "$50.000",
        "Observación": "",
        "Info": ""
    },
    {
        "Año": "2024",
        "Mes": "Septiembre",
        "Ciudad": "Santiago",
        "Día": "Viernes",
        "Institución Financiera": "Banco BICE",
        "Producto": "T. Crédito",
        "Marca de Tarjeta": "VISA",
        "Segmento": "",
        "Local": "Mia Bar",
        "Descuento": "40%",
        "Tope Descuento": "$50.000",
        "Observación": "",
        "Info": ""
    },
    {
        "Año": "2024",
        "Mes": "Septiembre",
        "Ciudad": "Santiago",
        "Día": "Sábado",
        "Institución Financiera": "Banco BICE",
        "Producto": "T. Crédito",
        "Marca de Tarjeta": "VISA",
        "Segmento": "Signature",
        "Local": "Zanzibar**",
        "Descuento": "50%",
        "Tope Descuento": "$80.000",
        "Observación": "",
        "Info": ""
    },
    {
        "Año": "2024",
        "Mes": "Septiembre",
        "Ciudad": "Santiago",
        "Día": "Domingo",
        "Institución Financiera": "Banco BICE",
        "Producto": "T. Crédito",
        "Marca de Tarjeta": "VISA",
        "Segmento": "Signature",
        "Local": "Kechua**",
        "Descuento": "50%",
        "Tope Descuento": "$80.000",
        "Observación": "",
        "Info": ""
    },
    {
        "Año": "2024",
        "Mes": "Septiembre",
        "Ciudad": "Santiago",
        "Día": "Jueves",
        "Institución Financiera": "Banco BICE",
        "Producto": "T. Crédito",
        "Marca de Tarjeta": "VISA",
        "Segmento": "Banca Joven",
        "Local": "Bar Santiago",
        "Descuento": "40%",
        "Tope Descuento": "$30.000",
        "Observación": "",
        "Info": "https://banco.bice.cl/personas/beneficios/bar-santiago"
    },
    {
        "Año": "2024",
        "Mes": "Septiembre",
        "Ciudad": "Santiago",
        "Día": "Lunes",
        "Institución Financiera": "Banco Security",
        "Producto": "T. Crédito",
        "Marca de Tarjeta": "",
        "Segmento": "ONE",
        "Local": "La Panera Rosa",
        "Descuento": "40%",
        "Tope Descuento": "$50.000",
        "Observación": "",
        "Info": ""
    },
    {
        "Año": "2024",
        "Mes": "Septiembre",
        "Ciudad": "Santiago",
        "Día": "Martes",
        "Institución Financiera": "Banco Security",
        "Producto": "T. Crédito",
        "Marca de Tarjeta": "",
        "Segmento": "ONE",
        "Local": "Cuerovaca",
        "Descuento": "40%",
        "Tope Descuento": "$50.000",
        "Observación": "",
        "Info": ""
    },
    {
        "Año": "2024",
        "Mes": "Septiembre",
        "Ciudad": "Santiago",
        "Día": "Miércoles",
        "Institución Financiera": "Banco Security",
        "Producto": "T. Crédito",
        "Marca de Tarjeta": "",
        "Segmento": "ONE",
        "Local": "Naoki",
        "Descuento": "40%",
        "Tope Descuento": "$50.000",
        "Observación": "",
        "Info": ""
    },
    {
        "Año": "2024",
        "Mes": "Septiembre",
        "Ciudad": "Santiago",
        "Día": "Jueves",
        "Institución Financiera": "Banco Security",
        "Producto": "T. Crédito",
        "Marca de Tarjeta": "",
        "Segmento": "ONE",
        "Local": "Barrica 94",
        "Descuento": "50%",
        "Tope Descuento": "$50.000",
        "Observación": "",
        "Info": ""
    },
    {
        "Año": "2024",
        "Mes": "Septiembre",
        "Ciudad": "Santiago",
        "Día": "Viernes",
        "Institución Financiera": "Banco Security",
        "Producto": "T. Crédito",
        "Marca de Tarjeta": "",
        "Segmento": "ONE",
        "Local": "Nkiru",
        "Descuento": "30%",
        "Tope Descuento": "$50.000",
        "Observación": "",
        "Info": ""
    },
    {
        "Año": "2024",
        "Mes": "Septiembre",
        "Ciudad": "Santiago",
        "Día": "Sábado",
        "Institución Financiera": "Banco Security",
        "Producto": "T. Crédito",
        "Marca de Tarjeta": "",
        "Segmento": "ONE",
        "Local": "Gi Restaurant",
        "Descuento": "30%",
        "Tope Descuento": "$50.000",
        "Observación": "",
        "Info": ""
    },
    {
        "Año": "2024",
        "Mes": "Septiembre",
        "Ciudad": "Santiago",
        "Día": "Domingo",
        "Institución Financiera": "Banco Security",
        "Producto": "T. Crédito",
        "Marca de Tarjeta": "",
        "Segmento": "ONE",
        "Local": "Sicily Pizzeria",
        "Descuento": "30%",
        "Tope Descuento": "$50.000",
        "Observación": "",
        "Info": ""
    },
    {
        "Año": "2024",
        "Mes": "Septiembre",
        "Ciudad": "Santiago",
        "Día": "Lunes",
        "Institución Financiera": "Banco Itaú",
        "Producto": "T. Crédito",
        "Marca de Tarjeta": "Mastercard",
        "Segmento": "Black",
        "Local": "Ciro's",
        "Descuento": "40%",
        "Tope Descuento": "$50.000",
        "Observación": "",
        "Info": ""
    },
    {
        "Año": "2024",
        "Mes": "Septiembre",
        "Ciudad": "Santiago",
        "Día": "Martes",
        "Institución Financiera": "Banco Itaú",
        "Producto": "T. Crédito",
        "Marca de Tarjeta": "Mastercard",
        "Segmento": "Black",
        "Local": "Infiltrados",
        "Descuento": "40%",
        "Tope Descuento": "$50.000",
        "Observación": "",
        "Info": ""
    },
    {
        "Año": "2024",
        "Mes": "Septiembre",
        "Ciudad": "Santiago",
        "Día": "Martes",
        "Institución Financiera": "Banco Itaú",
        "Producto": "T. Crédito",
        "Marca de Tarjeta": "Mastercard",
        "Segmento": "Black",
        "Local": "Tanaka",
        "Descuento": "40%",
        "Tope Descuento": "$50.000",
        "Observación": "",
        "Info": ""
    },
    {
        "Año": "2024",
        "Mes": "Septiembre",
        "Ciudad": "Santiago",
        "Día": "Miércoles",
        "Institución Financiera": "Banco Itaú",
        "Producto": "T. Crédito",
        "Marca de Tarjeta": "Mastercard",
        "Segmento": "Black",
        "Local": "Fukai",
        "Descuento": "40%",
        "Tope Descuento": "$50.000",
        "Observación": "",
        "Info": ""
    },
    {
        "Año": "2024",
        "Mes": "Septiembre",
        "Ciudad": "Santiago",
        "Día": "Jueves",
        "Institución Financiera": "Banco Itaú",
        "Producto": "T. Crédito",
        "Marca de Tarjeta": "Mastercard",
        "Segmento": "Black",
        "Local": "Casaluz",
        "Descuento": "40%",
        "Tope Descuento": "$50.000",
        "Observación": "",
        "Info": ""
    },
    {
        "Año": "2024",
        "Mes": "Septiembre",
        "Ciudad": "Santiago",
        "Día": "Jueves",
        "Institución Financiera": "Banco Itaú",
        "Producto": "T. Crédito",
        "Marca de Tarjeta": "Mastercard",
        "Segmento": "Black",
        "Local": "Hijo Del Sol",
        "Descuento": "40%",
        "Tope Descuento": "$50.000",
        "Observación": "",
        "Info": ""
    },
    {
        "Año": "2024",
        "Mes": "Septiembre",
        "Ciudad": "Santiago",
        "Día": "Viernes",
        "Institución Financiera": "Banco Itaú",
        "Producto": "T. Crédito",
        "Marca de Tarjeta": "Mastercard",
        "Segmento": "Black",
        "Local": "Siete Negronis",
        "Descuento": "40%",
        "Tope Descuento": "$50.000",
        "Observación": "",
        "Info": ""
    },
    {
        "Año": "2024",
        "Mes": "Septiembre",
        "Ciudad": "Santiago",
        "Día": "Lunes",
        "Institución Financiera": "Banco BICE",
        "Producto": "T. Débito",
        "Marca de Tarjeta": "",
        "Segmento": "",
        "Local": "Ambrosía",
        "Descuento": "40%",
        "Tope Descuento": "$50.000",
        "Observación": "",
        "Info": ""
    },
    {
        "Año": "2024",
        "Mes": "Septiembre",
        "Ciudad": "Santiago",
        "Día": "Martes",
        "Institución Financiera": "Banco BICE",
        "Producto": "T. Débito",
        "Marca de Tarjeta": "",
        "Segmento": "",
        "Local": "El Establo",
        "Descuento": "40%",
        "Tope Descuento": "$50.000",
        "Observación": "",
        "Info": ""
    },
    {
        "Año": "2024",
        "Mes": "Septiembre",
        "Ciudad": "Santiago",
        "Día": "Miércoles",
        "Institución Financiera": "Banco BICE",
        "Producto": "T. Débito",
        "Marca de Tarjeta": "",
        "Segmento": "",
        "Local": "Olam",
        "Descuento": "40%",
        "Tope Descuento": "$50.000",
        "Observación": "",
        "Info": ""
    },
    {
        "Año": "2024",
        "Mes": "Septiembre",
        "Ciudad": "Santiago",
        "Día": "Jueves",
        "Institución Financiera": "Banco BICE",
        "Producto": "T. Débito",
        "Marca de Tarjeta": "",
        "Segmento": "",
        "Local": "Bar Alonso",
        "Descuento": "40%",
        "Tope Descuento": "$50.000",
        "Observación": "",
        "Info": ""
    },
    {
        "Año": "2024",
        "Mes": "Septiembre",
        "Ciudad": "Santiago",
        "Día": "Viernes",
        "Institución Financiera": "Banco BICE",
        "Producto": "T. Débito",
        "Marca de Tarjeta": "",
        "Segmento": "",
        "Local": "Mia Bar",
        "Descuento": "40%",
        "Tope Descuento": "$50.000",
        "Observación": "",
        "Info": ""
    },
    {
        "Año": "2024",
        "Mes": "Septiembre",
        "Ciudad": "Santiago",
        "Día": "Sábado",
        "Institución Financiera": "Banco BICE",
        "Producto": "T. Crédito",
        "Marca de Tarjeta": "VISA",
        "Segmento": "Infinite",
        "Local": "Zanzibar**",
        "Descuento": "50%",
        "Tope Descuento": "$80.000",
        "Observación": "",
        "Info": ""
    },
    {
        "Año": "2024",
        "Mes": "Septiembre",
        "Ciudad": "Santiago",
        "Día": "Domingo",
        "Institución Financiera": "Banco BICE",
        "Producto": "T. Crédito",
        "Marca de Tarjeta": "VISA",
        "Segmento": "Infinite",
        "Local": "Kechua**",
        "Descuento": "50%",
        "Tope Descuento": "$80.000",
        "Observación": "",
        "Info": ""
    },
    {
        "Año": "2024",
        "Mes": "Septiembre",
        "Ciudad": "Santiago",
        "Día": "Lunes",
        "Institución Financiera": "Banco BICE",
        "Producto": "T. Débito",
        "Marca de Tarjeta": "VISA",
        "Segmento": "",
        "Local": "Ambrosía",
        "Descuento": "40%",
        "Tope Descuento": "$50.000",
        "Observación": "",
        "Info": ""
    },
    {
        "Año": "2024",
        "Mes": "Septiembre",
        "Ciudad": "Santiago",
        "Día": "Martes",
        "Institución Financiera": "Banco BICE",
        "Producto": "T. Débito",
        "Marca de Tarjeta": "VISA",
        "Segmento": "",
        "Local": "El Establo",
        "Descuento": "40%",
        "Tope Descuento": "$50.000",
        "Observación": "",
        "Info": ""
    },
    {
        "Año": "2024",
        "Mes": "Septiembre",
        "Ciudad": "Santiago",
        "Día": "Miércoles",
        "Institución Financiera": "Banco BICE",
        "Producto": "T. Débito",
        "Marca de Tarjeta": "VISA",
        "Segmento": "",
        "Local": "Olam",
        "Descuento": "40%",
        "Tope Descuento": "$50.000",
        "Observación": "",
        "Info": ""
    },
    {
        "Año": "2024",
        "Mes": "Septiembre",
        "Ciudad": "Santiago",
        "Día": "Jueves",
        "Institución Financiera": "Banco BICE",
        "Producto": "T. Débito",
        "Marca de Tarjeta": "VISA",
        "Segmento": "",
        "Local": "Bar Alonso",
        "Descuento": "40%",
        "Tope Descuento": "$50.000",
        "Observación": "",
        "Info": ""
    },
    {
        "Año": "2024",
        "Mes": "Septiembre",
        "Ciudad": "Santiago",
        "Día": "Viernes",
        "Institución Financiera": "Banco BICE",
        "Producto": "T. Débito",
        "Marca de Tarjeta": "VISA",
        "Segmento": "",
        "Local": "Mia Bar",
        "Descuento": "40%",
        "Tope Descuento": "$50.000",
        "Observación": "",
        "Info": ""
    },
    {
        "Año": "2024",
        "Mes": "Septiembre",
        "Ciudad": "Santiago",
        "Día": "Martes",
        "Institución Financiera": "Banco Falabella",
        "Producto": "T. Crédito",
        "Marca de Tarjeta": "",
        "Segmento": "",
        "Local": "Bar De Rio",
        "Descuento": "40%",
        "Tope Descuento": "",
        "Observación": "Sólo válido en Borde Río",
        "Info": ""
    },
    {
        "Año": "2024",
        "Mes": "Septiembre",
        "Ciudad": "Santiago",
        "Día": "Martes",
        "Institución Financiera": "Banco Falabella",
        "Producto": "T. Crédito",
        "Marca de Tarjeta": "",
        "Segmento": "",
        "Local": "Bar Santiago",
        "Descuento": "40%",
        "Tope Descuento": "",
        "Observación": "Sólo válido en Borde Río",
        "Info": ""
    },
    {
        "Año": "2024",
        "Mes": "Septiembre",
        "Ciudad": "Santiago",
        "Día": "Martes",
        "Institución Financiera": "Banco Falabella",
        "Producto": "T. Crédito",
        "Marca de Tarjeta": "",
        "Segmento": "",
        "Local": "Bistró & Café",
        "Descuento": "40%",
        "Tope Descuento": "",
        "Observación": "Sólo válido en Borde Río",
        "Info": ""
    },
    {
        "Año": "2024",
        "Mes": "Septiembre",
        "Ciudad": "Santiago",
        "Día": "Martes",
        "Institución Financiera": "Banco Falabella",
        "Producto": "T. Crédito",
        "Marca de Tarjeta": "",
        "Segmento": "",
        "Local": "Kechua",
        "Descuento": "40%",
        "Tope Descuento": "",
        "Observación": "Sólo válido en Borde Río",
        "Info": ""
    },
    {
        "Año": "2024",
        "Mes": "Septiembre",
        "Ciudad": "Santiago",
        "Día": "Martes",
        "Institución Financiera": "Banco Falabella",
        "Producto": "T. Crédito",
        "Marca de Tarjeta": "",
        "Segmento": "",
        "Local": "Krossbar",
        "Descuento": "40%",
        "Tope Descuento": "",
        "Observación": "Sólo válido en Borde Río",
        "Info": ""
    },
    {
        "Año": "2024",
        "Mes": "Septiembre",
        "Ciudad": "Santiago",
        "Día": "Martes",
        "Institución Financiera": "Banco Falabella",
        "Producto": "T. Crédito",
        "Marca de Tarjeta": "",
        "Segmento": "",
        "Local": "La Tabla",
        "Descuento": "40%",
        "Tope Descuento": "",
        "Observación": "Sólo válido en Borde Río",
        "Info": ""
    },
    {
        "Año": "2024",
        "Mes": "Septiembre",
        "Ciudad": "Santiago",
        "Día": "Martes",
        "Institución Financiera": "Banco Falabella",
        "Producto": "T. Crédito",
        "Marca de Tarjeta": "",
        "Segmento": "",
        "Local": "Pulmay",
        "Descuento": "40%",
        "Tope Descuento": "",
        "Observación": "Sólo válido en Borde Río",
        "Info": ""
    },
    {
        "Año": "2024",
        "Mes": "Septiembre",
        "Ciudad": "Santiago",
        "Día": "Martes",
        "Institución Financiera": "Banco Falabella",
        "Producto": "T. Crédito",
        "Marca de Tarjeta": "",
        "Segmento": "",
        "Local": "Zanzibar",
        "Descuento": "40%",
        "Tope Descuento": "",
        "Observación": "Sólo válido en Borde Río",
        "Info": ""
    },
    {
        "Año": "2024",
        "Mes": "Septiembre",
        "Ciudad": "Santiago",
        "Día": "Lunes",
        "Institución Financiera": "Banco Falabella",
        "Producto": "T. Crédito",
        "Marca de Tarjeta": "",
        "Segmento": "",
        "Local": "Berlin Doner Kebab",
        "Descuento": "40%",
        "Tope Descuento": "",
        "Observación": "",
        "Info": ""
    },
    {
        "Año": "2024",
        "Mes": "Septiembre",
        "Ciudad": "Santiago",
        "Día": "Miércoles",
        "Institución Financiera": "Banco Falabella",
        "Producto": "T. Crédito",
        "Marca de Tarjeta": "",
        "Segmento": "",
        "Local": "Nelí",
        "Descuento": "40%",
        "Tope Descuento": "",
        "Observación": "",
        "Info": ""
    },
    {
        "Año": "2024",
        "Mes": "Septiembre",
        "Ciudad": "Santiago",
        "Día": "Miércoles",
        "Institución Financiera": "Banco Falabella",
        "Producto": "T. Crédito",
        "Marca de Tarjeta": "",
        "Segmento": "",
        "Local": "Uncle Fletch",
        "Descuento": "40%",
        "Tope Descuento": "",
        "Observación": "",
        "Info": ""
    },
    {
        "Año": "2024",
        "Mes": "Septiembre",
        "Ciudad": "Santiago",
        "Día": "Jueves",
        "Institución Financiera": "Banco Falabella",
        "Producto": "T. Crédito",
        "Marca de Tarjeta": "",
        "Segmento": "",
        "Local": "Ciudad Vieja",
        "Descuento": "40%",
        "Tope Descuento": "",
        "Observación": "",
        "Info": ""
    },
    {
        "Año": "2024",
        "Mes": "Septiembre",
        "Ciudad": "Santiago",
        "Día": "Viernes",
        "Institución Financiera": "Banco Falabella",
        "Producto": "T. Crédito",
        "Marca de Tarjeta": "",
        "Segmento": "",
        "Local": "Ково",
        "Descuento": "40%",
        "Tope Descuento": "",
        "Observación": "",
        "Info": ""
    },
    {
        "Año": "2024",
        "Mes": "Septiembre",
        "Ciudad": "Santiago",
        "Día": "Lunes, Miércoles",
        "Institución Financiera": "Banco Falabella",
        "Producto": "T. Crédito",
        "Marca de Tarjeta": "",
        "Segmento": "",
        "Local": "Danés",
        "Descuento": "40%",
        "Tope Descuento": "",
        "Observación": "",
        "Info": ""
    },
    {
        "Año": "2024",
        "Mes": "Septiembre",
        "Ciudad": "Santiago",
        "Día": "Lunes, Miércoles",
        "Institución Financiera": "Banco Falabella",
        "Producto": "T. Crédito",
        "Marca de Tarjeta": "",
        "Segmento": "",
        "Local": "La Mestranza",
        "Descuento": "40%",
        "Tope Descuento": "",
        "Observación": "",
        "Info": ""
    },
    {
        "Año": "2024",
        "Mes": "Septiembre",
        "Ciudad": "Santiago",
        "Día": "Lunes, Miércoles, Viernes, Sábado, Domingo",
        "Institución Financiera": "Banco Falabella",
        "Producto": "T. Crédito",
        "Marca de Tarjeta": "",
        "Segmento": "",
        "Local": "Vapiano",
        "Descuento": "40%",
        "Tope Descuento": "",
        "Observación": "",
        "Info": ""
    },
    {
        "Año": "2024",
        "Mes": "Septiembre",
        "Ciudad": "Santiago",
        "Día": "Miércoles, Jueves, Viernes, Sábado",
        "Institución Financiera": "Banco Falabella",
        "Producto": "T. Crédito",
        "Marca de Tarjeta": "",
        "Segmento": "",
        "Local": "El Japonés",
        "Descuento": "40%",
        "Tope Descuento": "",
        "Observación": "Sólo en Open Kennedy desde las 19:30 hrs",
        "Info": ""
    },
    {
        "Año": "2024",
        "Mes": "Septiembre",
        "Ciudad": "Santiago",
        "Día": "Miércoles, Jueves, Viernes, Sábado",
        "Institución Financiera": "Banco Falabella",
        "Producto": "T. Crédito",
        "Marca de Tarjeta": "",
        "Segmento": "",
        "Local": "La Piazza",
        "Descuento": "40%",
        "Tope Descuento": "",
        "Observación": "Sólo en Open Kennedy desde las 19:30 hrs",
        "Info": ""
    },
    {
        "Año": "2024",
        "Mes": "Septiembre",
        "Ciudad": "Santiago",
        "Día": "Miércoles, Jueves, Viernes, Sábado",
        "Institución Financiera": "Banco Falabella",
        "Producto": "T. Crédito",
        "Marca de Tarjeta": "",
        "Segmento": "",
        "Local": "Siete Cortes",
        "Descuento": "40%",
        "Tope Descuento": "",
        "Observación": "Sólo en Open Kennedy desde las 19:30 hrs",
        "Info": ""
    },
    {
        "Año": "2024",
        "Mes": "Septiembre",
        "Ciudad": "Santiago",
        "Día": "Miércoles, Jueves, Viernes, Sábado",
        "Institución Financiera": "Banco Falabella",
        "Producto": "T. Crédito",
        "Marca de Tarjeta": "",
        "Segmento": "",
        "Local": "Jalisco",
        "Descuento": "40%",
        "Tope Descuento": "",
        "Observación": "Sólo en Open Kennedy desde las 19:30 hrs",
        "Info": ""
    },
    {
        "Año": "2024",
        "Mes": "Septiembre",
        "Ciudad": "Santiago",
        "Día": "Miércoles, Jueves, Viernes, Sábado",
        "Institución Financiera": "Banco Falabella",
        "Producto": "T. Crédito",
        "Marca de Tarjeta": "",
        "Segmento": "",
        "Local": "La Sanguchera del Barrio",
        "Descuento": "40%",
        "Tope Descuento": "",
        "Observación": "Sólo en Open Kennedy desde las 19:30 hrs",
        "Info": ""
    },
    {
        "Año": "2024",
        "Mes": "Septiembre",
        "Ciudad": "Santiago",
        "Día": "Miércoles, Jueves, Viernes, Sábado",
        "Institución Financiera": "Banco Falabella",
        "Producto": "T. Crédito",
        "Marca de Tarjeta": "",
        "Segmento": "",
        "Local": "El Bodegón",
        "Descuento": "40%",
        "Tope Descuento": "",
        "Observación": "Sólo en Open Kennedy desde las 19:30 hrs",
        "Info": ""
    },
    {
        "Año": "2024",
        "Mes": "Septiembre",
        "Ciudad": "Santiago",
        "Día": "Miércoles, Jueves, Viernes, Sábado",
        "Institución Financiera": "Banco Falabella",
        "Producto": "T. Crédito",
        "Marca de Tarjeta": "",
        "Segmento": "",
        "Local": "Mesón del Marinero",
        "Descuento": "40%",
        "Tope Descuento": "",
        "Observación": "Sólo en Open Kennedy desde las 19:30 hrs",
        "Info": ""
    },
    {
        "Año": "2024",
        "Mes": "Septiembre",
        "Ciudad": "Santiago",
        "Día": "Sábado, Domingo",
        "Institución Financiera": "Banco Falabella",
        "Producto": "T. Crédito",
        "Marca de Tarjeta": "",
        "Segmento": "",
        "Local": "Cantina Isidora",
        "Descuento": "40%",
        "Tope Descuento": "",
        "Observación": "Sólo en Isidora Goyenechea",
        "Info": ""
    },
    {
        "Año": "2024",
        "Mes": "Septiembre",
        "Ciudad": "Santiago",
        "Día": "Sábado, Domingo",
        "Institución Financiera": "Banco Falabella",
        "Producto": "T. Crédito",
        "Marca de Tarjeta": "",
        "Segmento": "",
        "Local": "Muu Steak",
        "Descuento": "40%",
        "Tope Descuento": "",
        "Observación": "Sólo en Isidora Goyenechea",
        "Info": ""
    },
    {
        "Año": "2024",
        "Mes": "Septiembre",
        "Ciudad": "Santiago",
        "Día": "Sábado, Domingo",
        "Institución Financiera": "Banco Falabella",
        "Producto": "T. Crédito",
        "Marca de Tarjeta": "",
        "Segmento": "",
        "Local": "Tanta",
        "Descuento": "40%",
        "Tope Descuento": "",
        "Observación": "Sólo en Isidora Goyenechea",
        "Info": ""
    },
    {
        "Año": "2024",
        "Mes": "Septiembre",
        "Ciudad": "Santiago",
        "Día": "Lunes, Martes, Miércoles, Jueves, Viernes",
        "Institución Financiera": "Banco Falabella",
        "Producto": "T. Crédito",
        "Marca de Tarjeta": "",
        "Segmento": "",
        "Local": "Selección Mall Plaza",
        "Descuento": "40%",
        "Tope Descuento": "",
        "Observación": "",
        "Info": "https://www.bancofalabella.cl/descuentos/detalle/40-de-dcto-en-restaurantes-mallplaza"
    },
    {
        "Año": "2024",
        "Mes": "Septiembre",
        "Ciudad": "Santiago",
        "Día": "Lunes",
        "Institución Financiera": "Banco Falabella",
        "Producto": "T. Crédito",
        "Marca de Tarjeta": "",
        "Segmento": "CMR Elite",
        "Local": "Naoki",
        "Descuento": "40%",
        "Tope Descuento": "",
        "Observación": "",
        "Info": ""
    },
    {
        "Año": "2024",
        "Mes": "Septiembre",
        "Ciudad": "Santiago",
        "Día": "Martes",
        "Institución Financiera": "Banco Falabella",
        "Producto": "T. Crédito",
        "Marca de Tarjeta": "",
        "Segmento": "CMR Elite",
        "Local": "Ceiba",
        "Descuento": "40%",
        "Tope Descuento": "",
        "Observación": "",
        "Info": ""
    },
    {
        "Año": "2024",
        "Mes": "Septiembre",
        "Ciudad": "Santiago",
        "Día": "Jueves",
        "Institución Financiera": "Banco Falabella",
        "Producto": "T. Crédito",
        "Marca de Tarjeta": "",
        "Segmento": "CMR Elite",
        "Local": "La Dicha",
        "Descuento": "40%",
        "Tope Descuento": "",
        "Observación": "",
        "Info": ""
    },
    {
        "Año": "2024",
        "Mes": "Septiembre",
        "Ciudad": "Santiago",
        "Día": "Jueves",
        "Institución Financiera": "Banco Falabella",
        "Producto": "T. Crédito",
        "Marca de Tarjeta": "",
        "Segmento": "CMR Elite",
        "Local": "La Picanteria",
        "Descuento": "40%",
        "Tope Descuento": "",
        "Observación": "",
        "Info": ""
    },
    {
        "Año": "2024",
        "Mes": "Septiembre",
        "Ciudad": "Santiago",
        "Día": "Viernes",
        "Institución Financiera": "Banco Falabella",
        "Producto": "T. Crédito",
        "Marca de Tarjeta": "",
        "Segmento": "CMR Elite",
        "Local": "Ciro's",
        "Descuento": "40%",
        "Tope Descuento": "",
        "Observación": "",
        "Info": ""
    },
    {
        "Año": "2024",
        "Mes": "Septiembre",
        "Ciudad": "Santiago",
        "Día": "Lunes",
        "Institución Financiera": "Scotiabank",
        "Producto": "T. Crédito",
        "Marca de Tarjeta": "VISA",
        "Segmento": "Signature, Infinite Wealth Management",
        "Local": "Carmine",
        "Descuento": "40%",
        "Tope Descuento": "",
        "Observación": "",
        "Info": ""
    },
    {
        "Año": "2024",
        "Mes": "Septiembre",
        "Ciudad": "Santiago",
        "Día": "Lunes",
        "Institución Financiera": "Scotiabank",
        "Producto": "T. Crédito",
        "Marca de Tarjeta": "VISA",
        "Segmento": "Signature, Infinite Wealth Management",
        "Local": "Sabor Y Aroma",
        "Descuento": "50%",
        "Tope Descuento": "",
        "Observación": "",
        "Info": ""
    },
    {
        "Año": "2024",
        "Mes": "Septiembre",
        "Ciudad": "Santiago",
        "Día": "Martes",
        "Institución Financiera": "Scotiabank",
        "Producto": "T. Crédito",
        "Marca de Tarjeta": "VISA",
        "Segmento": "Signature, Infinite Wealth Management",
        "Local": "El Meson De La Pat.",
        "Descuento": "50%",
        "Tope Descuento": "",
        "Observación": "",
        "Info": ""
    },
    {
        "Año": "2024",
        "Mes": "Septiembre",
        "Ciudad": "Santiago",
        "Día": "Martes",
        "Institución Financiera": "Scotiabank",
        "Producto": "T. Crédito",
        "Marca de Tarjeta": "VISA",
        "Segmento": "Signature, Infinite Wealth Management",
        "Local": "Piso Uno",
        "Descuento": "50%",
        "Tope Descuento": "",
        "Observación": "",
        "Info": ""
    },
    {
        "Año": "2024",
        "Mes": "Septiembre",
        "Ciudad": "Santiago",
        "Día": "Martes",
        "Institución Financiera": "Scotiabank",
        "Producto": "T. Crédito",
        "Marca de Tarjeta": "VISA",
        "Segmento": "Signature, Infinite Wealth Management",
        "Local": "Yma",
        "Descuento": "40%",
        "Tope Descuento": "",
        "Observación": "",
        "Info": ""
    },
    {
        "Año": "2024",
        "Mes": "Septiembre",
        "Ciudad": "Santiago",
        "Día": "Miércoles",
        "Institución Financiera": "Scotiabank",
        "Producto": "T. Crédito",
        "Marca de Tarjeta": "VISA",
        "Segmento": "Signature, Infinite Wealth Management",
        "Local": "Consenza",
        "Descuento": "40%",
        "Tope Descuento": "",
        "Observación": "",
        "Info": ""
    },
    {
        "Año": "2024",
        "Mes": "Septiembre",
        "Ciudad": "Santiago",
        "Día": "Miércoles",
        "Institución Financiera": "Scotiabank",
        "Producto": "T. Crédito",
        "Marca de Tarjeta": "VISA",
        "Segmento": "Signature, Infinite Wealth Management",
        "Local": "Taringa",
        "Descuento": "50%",
        "Tope Descuento": "",
        "Observación": "",
        "Info": ""
    },
    {
        "Año": "2024",
        "Mes": "Septiembre",
        "Ciudad": "Santiago",
        "Día": "Jueves",
        "Institución Financiera": "Scotiabank",
        "Producto": "T. Crédito",
        "Marca de Tarjeta": "VISA",
        "Segmento": "Signature, Infinite Wealth Management",
        "Local": "De Pura Madre",
        "Descuento": "40%",
        "Tope Descuento": "",
        "Observación": "",
        "Info": ""
    },
    {
        "Año": "2024",
        "Mes": "Septiembre",
        "Ciudad": "Santiago",
        "Día": "Jueves",
        "Institución Financiera": "Scotiabank",
        "Producto": "T. Crédito",
        "Marca de Tarjeta": "VISA",
        "Segmento": "Signature, Infinite Wealth Management",
        "Local": "Santa Brasa",
        "Descuento": "50%",
        "Tope Descuento": "",
        "Observación": "",
        "Info": ""
    },
    {
        "Año": "2024",
        "Mes": "Septiembre",
        "Ciudad": "Santiago",
        "Día": "Viernes",
        "Institución Financiera": "Scotiabank",
        "Producto": "T. Crédito",
        "Marca de Tarjeta": "VISA",
        "Segmento": "Signature, Infinite Wealth Management",
        "Local": "Estación 59",
        "Descuento": "50%",
        "Tope Descuento": "",
        "Observación": "",
        "Info": ""
    },
    {
        "Año": "2024",
        "Mes": "Septiembre",
        "Ciudad": "Santiago",
        "Día": "Viernes",
        "Institución Financiera": "Scotiabank",
        "Producto": "T. Crédito",
        "Marca de Tarjeta": "VISA",
        "Segmento": "Signature, Infinite Wealth Management",
        "Local": "Pomeriggio",
        "Descuento": "40%",
        "Tope Descuento": "",
        "Observación": "",
        "Info": ""
    },
    {
        "Año": "2024",
        "Mes": "Septiembre",
        "Ciudad": "Santiago",
        "Día": "Sábado",
        "Institución Financiera": "Scotiabank",
        "Producto": "T. Crédito",
        "Marca de Tarjeta": "VISA",
        "Segmento": "Signature, Infinite Wealth Management",
        "Local": "Karai",
        "Descuento": "50%",
        "Tope Descuento": "",
        "Observación": "",
        "Info": ""
    },
    {
        "Año": "2024",
        "Mes": "Septiembre",
        "Ciudad": "Santiago",
        "Día": "Sábado",
        "Institución Financiera": "Scotiabank",
        "Producto": "T. Crédito",
        "Marca de Tarjeta": "VISA",
        "Segmento": "Signature, Infinite Wealth Management",
        "Local": "Pasta Basta",
        "Descuento": "50%",
        "Tope Descuento": "",
        "Observación": "",
        "Info": ""
    },
    {
        "Año": "2024",
        "Mes": "Septiembre",
        "Ciudad": "Santiago",
        "Día": "Domingo",
        "Institución Financiera": "Scotiabank",
        "Producto": "T. Crédito",
        "Marca de Tarjeta": "VISA",
        "Segmento": "Signature, Infinite Wealth Management",
        "Local": "Rishtedar",
        "Descuento": "50%",
        "Tope Descuento": "",
        "Observación": "",
        "Info": ""
    },
    {
        "Año": "2024",
        "Mes": "Septiembre",
        "Ciudad": "Santiago",
        "Día": "Martes",
        "Institución Financiera": "Banco Falabella",
        "Producto": "T. Débito",
        "Marca de Tarjeta": "",
        "Segmento": "",
        "Local": "Bar De Rio",
        "Descuento": "30%",
        "Tope Descuento": "",
        "Observación": "",
        "Info": ""
    },
    {
        "Año": "2024",
        "Mes": "Septiembre",
        "Ciudad": "Santiago",
        "Día": "Martes",
        "Institución Financiera": "Banco Falabella",
        "Producto": "T. Débito",
        "Marca de Tarjeta": "",
        "Segmento": "",
        "Local": "Bar Santiago",
        "Descuento": "30%",
        "Tope Descuento": "",
        "Observación": "",
        "Info": ""
    },
    {
        "Año": "2024",
        "Mes": "Septiembre",
        "Ciudad": "Santiago",
        "Día": "Martes",
        "Institución Financiera": "Banco Falabella",
        "Producto": "T. Débito",
        "Marca de Tarjeta": "",
        "Segmento": "",
        "Local": "Bistró & Café",
        "Descuento": "30%",
        "Tope Descuento": "",
        "Observación": "",
        "Info": ""
    },
    {
        "Año": "2024",
        "Mes": "Septiembre",
        "Ciudad": "Santiago",
        "Día": "Martes",
        "Institución Financiera": "Banco Falabella",
        "Producto": "T. Débito",
        "Marca de Tarjeta": "",
        "Segmento": "",
        "Local": "Kechua",
        "Descuento": "30%",
        "Tope Descuento": "",
        "Observación": "",
        "Info": ""
    },
    {
        "Año": "2024",
        "Mes": "Septiembre",
        "Ciudad": "Santiago",
        "Día": "Martes",
        "Institución Financiera": "Banco Falabella",
        "Producto": "T. Débito",
        "Marca de Tarjeta": "",
        "Segmento": "",
        "Local": "Krossbar",
        "Descuento": "30%",
        "Tope Descuento": "",
        "Observación": "",
        "Info": ""
    },
    {
        "Año": "2024",
        "Mes": "Septiembre",
        "Ciudad": "Santiago",
        "Día": "Martes",
        "Institución Financiera": "Banco Falabella",
        "Producto": "T. Débito",
        "Marca de Tarjeta": "",
        "Segmento": "",
        "Local": "La Tabla",
        "Descuento": "30%",
        "Tope Descuento": "",
        "Observación": "",
        "Info": ""
    },
    {
        "Año": "2024",
        "Mes": "Septiembre",
        "Ciudad": "Santiago",
        "Día": "Martes",
        "Institución Financiera": "Banco Falabella",
        "Producto": "T. Débito",
        "Marca de Tarjeta": "",
        "Segmento": "",
        "Local": "Pulmay",
        "Descuento": "30%",
        "Tope Descuento": "",
        "Observación": "",
        "Info": ""
    },
    {
        "Año": "2024",
        "Mes": "Septiembre",
        "Ciudad": "Santiago",
        "Día": "Martes",
        "Institución Financiera": "Banco Falabella",
        "Producto": "T. Débito",
        "Marca de Tarjeta": "",
        "Segmento": "",
        "Local": "Zanzibar",
        "Descuento": "30%",
        "Tope Descuento": "",
        "Observación": "",
        "Info": ""
    },
    {
        "Año": "2024",
        "Mes": "Septiembre",
        "Ciudad": "Santiago",
        "Día": "Lunes",
        "Institución Financiera": "Banco Falabella",
        "Producto": "T. Débito",
        "Marca de Tarjeta": "",
        "Segmento": "",
        "Local": "Berlin Doner Kebab",
        "Descuento": "30%",
        "Tope Descuento": "",
        "Observación": "",
        "Info": ""
    },
    {
        "Año": "2024",
        "Mes": "Septiembre",
        "Ciudad": "Santiago",
        "Día": "Miércoles",
        "Institución Financiera": "Banco Falabella",
        "Producto": "T. Débito",
        "Marca de Tarjeta": "",
        "Segmento": "",
        "Local": "Nelí",
        "Descuento": "30%",
        "Tope Descuento": "",
        "Observación": "",
        "Info": ""
    },
    {
        "Año": "2024",
        "Mes": "Septiembre",
        "Ciudad": "Santiago",
        "Día": "Miércoles",
        "Institución Financiera": "Banco Falabella",
        "Producto": "T. Débito",
        "Marca de Tarjeta": "",
        "Segmento": "",
        "Local": "Uncle Fletch",
        "Descuento": "30%",
        "Tope Descuento": "",
        "Observación": "",
        "Info": ""
    },
    {
        "Año": "2024",
        "Mes": "Septiembre",
        "Ciudad": "Santiago",
        "Día": "Jueves",
        "Institución Financiera": "Banco Falabella",
        "Producto": "T. Débito",
        "Marca de Tarjeta": "",
        "Segmento": "",
        "Local": "Ciudad Vieja",
        "Descuento": "30%",
        "Tope Descuento": "",
        "Observación": "",
        "Info": ""
    },
    {
        "Año": "2024",
        "Mes": "Septiembre",
        "Ciudad": "Santiago",
        "Día": "Viernes",
        "Institución Financiera": "Banco Falabella",
        "Producto": "T. Débito",
        "Marca de Tarjeta": "",
        "Segmento": "",
        "Local": "Ково",
        "Descuento": "30%",
        "Tope Descuento": "",
        "Observación": "",
        "Info": ""
    },
    {
        "Año": "2024",
        "Mes": "Septiembre",
        "Ciudad": "Santiago",
        "Día": "Lunes, Miércoles",
        "Institución Financiera": "Banco Falabella",
        "Producto": "T. Débito",
        "Marca de Tarjeta": "",
        "Segmento": "",
        "Local": "Danés",
        "Descuento": "30%",
        "Tope Descuento": "",
        "Observación": "",
        "Info": ""
    },
    {
        "Año": "2024",
        "Mes": "Septiembre",
        "Ciudad": "Santiago",
        "Día": "Lunes, Miércoles",
        "Institución Financiera": "Banco Falabella",
        "Producto": "T. Débito",
        "Marca de Tarjeta": "",
        "Segmento": "",
        "Local": "La Mestranza",
        "Descuento": "30%",
        "Tope Descuento": "",
        "Observación": "",
        "Info": ""
    },
    {
        "Año": "2024",
        "Mes": "Septiembre",
        "Ciudad": "Santiago",
        "Día": "Lunes, Miércoles, Viernes, Sábado, Domingo",
        "Institución Financiera": "Banco Falabella",
        "Producto": "T. Débito",
        "Marca de Tarjeta": "",
        "Segmento": "",
        "Local": "Vapiano",
        "Descuento": "30%",
        "Tope Descuento": "",
        "Observación": "",
        "Info": ""
    },
    {
        "Año": "2024",
        "Mes": "Septiembre",
        "Ciudad": "Santiago",
        "Día": "Miércoles, Jueves, Viernes, Sábado",
        "Institución Financiera": "Banco Falabella",
        "Producto": "T. Débito",
        "Marca de Tarjeta": "",
        "Segmento": "",
        "Local": "El Japonés",
        "Descuento": "30%",
        "Tope Descuento": "",
        "Observación": "",
        "Info": ""
    },
    {
        "Año": "2024",
        "Mes": "Septiembre",
        "Ciudad": "Santiago",
        "Día": "Miércoles, Jueves, Viernes, Sábado",
        "Institución Financiera": "Banco Falabella",
        "Producto": "T. Débito",
        "Marca de Tarjeta": "",
        "Segmento": "",
        "Local": "La Piazza",
        "Descuento": "30%",
        "Tope Descuento": "",
        "Observación": "",
        "Info": ""
    },
    {
        "Año": "2024",
        "Mes": "Septiembre",
        "Ciudad": "Santiago",
        "Día": "Miércoles, Jueves, Viernes, Sábado",
        "Institución Financiera": "Banco Falabella",
        "Producto": "T. Débito",
        "Marca de Tarjeta": "",
        "Segmento": "",
        "Local": "Siete Cortes",
        "Descuento": "30%",
        "Tope Descuento": "",
        "Observación": "",
        "Info": ""
    },
    {
        "Año": "2024",
        "Mes": "Septiembre",
        "Ciudad": "Santiago",
        "Día": "Miércoles, Jueves, Viernes, Sábado",
        "Institución Financiera": "Banco Falabella",
        "Producto": "T. Débito",
        "Marca de Tarjeta": "",
        "Segmento": "",
        "Local": "Jalisco",
        "Descuento": "30%",
        "Tope Descuento": "",
        "Observación": "",
        "Info": ""
    },
    {
        "Año": "2024",
        "Mes": "Septiembre",
        "Ciudad": "Santiago",
        "Día": "Miércoles, Jueves, Viernes, Sábado",
        "Institución Financiera": "Banco Falabella",
        "Producto": "T. Débito",
        "Marca de Tarjeta": "",
        "Segmento": "",
        "Local": "La Sanguchera del Barrio",
        "Descuento": "30%",
        "Tope Descuento": "",
        "Observación": "",
        "Info": ""
    },
    {
        "Año": "2024",
        "Mes": "Septiembre",
        "Ciudad": "Santiago",
        "Día": "Miércoles, Jueves, Viernes, Sábado",
        "Institución Financiera": "Banco Falabella",
        "Producto": "T. Débito",
        "Marca de Tarjeta": "",
        "Segmento": "",
        "Local": "El Bodegón",
        "Descuento": "30%",
        "Tope Descuento": "",
        "Observación": "",
        "Info": ""
    },
    {
        "Año": "2024",
        "Mes": "Septiembre",
        "Ciudad": "Santiago",
        "Día": "Miércoles, Jueves, Viernes, Sábado",
        "Institución Financiera": "Banco Falabella",
        "Producto": "T. Débito",
        "Marca de Tarjeta": "",
        "Segmento": "",
        "Local": "Mesón del Marinero",
        "Descuento": "30%",
        "Tope Descuento": "",
        "Observación": "",
        "Info": ""
    },
    {
        "Año": "2024",
        "Mes": "Septiembre",
        "Ciudad": "Santiago",
        "Día": "Sábado, Domingo",
        "Institución Financiera": "Banco Falabella",
        "Producto": "T. Débito",
        "Marca de Tarjeta": "",
        "Segmento": "",
        "Local": "Cantina Isidora",
        "Descuento": "30%",
        "Tope Descuento": "",
        "Observación": "",
        "Info": ""
    },
    {
        "Año": "2024",
        "Mes": "Septiembre",
        "Ciudad": "Santiago",
        "Día": "Sábado, Domingo",
        "Institución Financiera": "Banco Falabella",
        "Producto": "T. Débito",
        "Marca de Tarjeta": "",
        "Segmento": "",
        "Local": "Muu Steak",
        "Descuento": "30%",
        "Tope Descuento": "",
        "Observación": "",
        "Info": ""
    },
    {
        "Año": "2024",
        "Mes": "Septiembre",
        "Ciudad": "Santiago",
        "Día": "Sábado, Domingo",
        "Institución Financiera": "Banco Falabella",
        "Producto": "T. Débito",
        "Marca de Tarjeta": "",
        "Segmento": "",
        "Local": "Tanta",
        "Descuento": "30%",
        "Tope Descuento": "",
        "Observación": "",
        "Info": ""
    },
    {
        "Año": "2024",
        "Mes": "Septiembre",
        "Ciudad": "Santiago",
        "Día": "Lunes, Martes, Miércoles, Jueves, Viernes",
        "Institución Financiera": "Banco Falabella",
        "Producto": "T. Débito",
        "Marca de Tarjeta": "",
        "Segmento": "",
        "Local": "Selección Mall Plaza",
        "Descuento": "30%",
        "Tope Descuento": "",
        "Observación": "",
        "Info": ""
    },
    {
        "Año": "2024",
        "Mes": "Septiembre",
        "Ciudad": "Santiago",
        "Día": "Lunes, Martes, Miércoles, Jueves",
        "Institución Financiera": "Copec Pay",
        "Producto": "T. Crédito",
        "Marca de Tarjeta": "Mastercard",
        "Segmento": "",
        "Local": "Streat Burger",
        "Descuento": "30%",
        "Tope Descuento": "",
        "Observación": "",
        "Info": ""
    },
    {
        "Año": "2024",
        "Mes": "Septiembre",
        "Ciudad": "Santiago",
        "Día": "Jueves, Viernes",
        "Institución Financiera": "Cencosud-Scotia",
        "Producto": "T. Crédito",
        "Marca de Tarjeta": "",
        "Segmento": "",
        "Local": "Cenco Mall Restaurantes",
        "Descuento": "40%",
        "Tope Descuento": "$50.000",
        "Observación": "Desde 19 hrs",
        "Info": ""
    },
    {
        "Año": "2024",
        "Mes": "Septiembre",
        "Ciudad": "Santiago",
        "Día": "Jueves, Viernes",
        "Institución Financiera": "Cencosud-Scotia",
        "Producto": "T. Crédito",
        "Marca de Tarjeta": "",
        "Segmento": "",
        "Local": "Selección Mirador del Alto",
        "Descuento": "40%",
        "Tope Descuento": "$50.000",
        "Observación": "Desde 19 hrs",
        "Info": ""
    },
    {
        "Año": "2024",
        "Mes": "Septiembre",
        "Ciudad": "Santiago",
        "Día": "Martes",
        "Institución Financiera": "Banco BCI",
        "Producto": "T. Crédito",
        "Marca de Tarjeta": "",
        "Segmento": "",
        "Local": "Chilis",
        "Descuento": "40%",
        "Tope Descuento": "$40.000",
        "Observación": "",
        "Info": ""
    },
    {
        "Año": "2024",
        "Mes": "Septiembre",
        "Ciudad": "Santiago",
        "Día": "Martes",
        "Institución Financiera": "Banco BCI",
        "Producto": "T. Crédito",
        "Marca de Tarjeta": "",
        "Segmento": "",
        "Local": "PF Chang's",
        "Descuento": "40%",
        "Tope Descuento": "$40.000",
        "Observación": "",
        "Info": ""
    },
    {
        "Año": "2024",
        "Mes": "Septiembre",
        "Ciudad": "Santiago",
        "Día": "Jueves",
        "Institución Financiera": "Banco BCI",
        "Producto": "T. Crédito",
        "Marca de Tarjeta": "",
        "Segmento": "",
        "Local": "Cocina de Javier",
        "Descuento": "40%",
        "Tope Descuento": "$40.000",
        "Observación": "",
        "Info": ""
    },
    {
        "Año": "2024",
        "Mes": "Septiembre",
        "Ciudad": "Santiago",
        "Día": "Jueves",
        "Institución Financiera": "Banco BCI",
        "Producto": "T. Crédito",
        "Marca de Tarjeta": "",
        "Segmento": "",
        "Local": "Galpon Alonso",
        "Descuento": "40%",
        "Tope Descuento": "$40.000",
        "Observación": "",
        "Info": ""
    },
    {
        "Año": "2024",
        "Mes": "Septiembre",
        "Ciudad": "Santiago",
        "Día": "Jueves",
        "Institución Financiera": "Banco BCI",
        "Producto": "T. Crédito",
        "Marca de Tarjeta": "",
        "Segmento": "",
        "Local": "Latin Hotel Marriot",
        "Descuento": "50%",
        "Tope Descuento": "$40.000",
        "Observación": "",
        "Info": ""
    },
    {
        "Año": "2024",
        "Mes": "Septiembre",
        "Ciudad": "Santiago",
        "Día": "Jueves",
        "Institución Financiera": "Banco BCI",
        "Producto": "T. Crédito",
        "Marca de Tarjeta": "",
        "Segmento": "",
        "Local": "Majka",
        "Descuento": "40%",
        "Tope Descuento": "$40.000",
        "Observación": "",
        "Info": ""
    },
    {
        "Año": "2024",
        "Mes": "Septiembre",
        "Ciudad": "Santiago",
        "Día": "Jueves",
        "Institución Financiera": "Banco BCI",
        "Producto": "T. Crédito",
        "Marca de Tarjeta": "",
        "Segmento": "",
        "Local": "Malva Loca",
        "Descuento": "40%",
        "Tope Descuento": "$40.000",
        "Observación": "",
        "Info": ""
    },
    {
        "Año": "2024",
        "Mes": "Septiembre",
        "Ciudad": "Santiago",
        "Día": "Jueves",
        "Institución Financiera": "Banco BCI",
        "Producto": "T. Crédito",
        "Marca de Tarjeta": "",
        "Segmento": "",
        "Local": "Pomeriggio",
        "Descuento": "40%",
        "Tope Descuento": "$40.000",
        "Observación": "",
        "Info": ""
    },
    {
        "Año": "2024",
        "Mes": "Septiembre",
        "Ciudad": "Santiago",
        "Día": "Jueves",
        "Institución Financiera": "Banco BCI",
        "Producto": "T. Crédito",
        "Marca de Tarjeta": "",
        "Segmento": "",
        "Local": "Puerto Del Alto",
        "Descuento": "40%",
        "Tope Descuento": "$40.000",
        "Observación": "",
        "Info": ""
    },
    {
        "Año": "2024",
        "Mes": "Septiembre",
        "Ciudad": "Santiago",
        "Día": "Jueves",
        "Institución Financiera": "Banco BCI",
        "Producto": "T. Crédito",
        "Marca de Tarjeta": "",
        "Segmento": "",
        "Local": "Tomata",
        "Descuento": "40%",
        "Tope Descuento": "$40.000",
        "Observación": "",
        "Info": ""
    },
    {
        "Año": "2024",
        "Mes": "Septiembre",
        "Ciudad": "Santiago",
        "Día": "Viernes",
        "Institución Financiera": "Banco BCI",
        "Producto": "T. Crédito",
        "Marca de Tarjeta": "",
        "Segmento": "",
        "Local": "Cuerovaca",
        "Descuento": "40%",
        "Tope Descuento": "$40.000",
        "Observación": "",
        "Info": ""
    },
    {
        "Año": "2024",
        "Mes": "Septiembre",
        "Ciudad": "Santiago",
        "Día": "Viernes",
        "Institución Financiera": "Banco BCI",
        "Producto": "T. Crédito",
        "Marca de Tarjeta": "",
        "Segmento": "",
        "Local": "Kantu",
        "Descuento": "40%",
        "Tope Descuento": "$40.000",
        "Observación": "",
        "Info": ""
    },
    {
        "Año": "2024",
        "Mes": "Septiembre",
        "Ciudad": "Santiago",
        "Día": "Viernes",
        "Institución Financiera": "Banco BCI",
        "Producto": "T. Crédito",
        "Marca de Tarjeta": "",
        "Segmento": "",
        "Local": "La Biferia",
        "Descuento": "40%",
        "Tope Descuento": "$40.000",
        "Observación": "",
        "Info": ""
    },
    {
        "Año": "2024",
        "Mes": "Septiembre",
        "Ciudad": "Santiago",
        "Día": "Viernes",
        "Institución Financiera": "Banco BCI",
        "Producto": "T. Crédito",
        "Marca de Tarjeta": "",
        "Segmento": "",
        "Local": "La Picantería",
        "Descuento": "40%",
        "Tope Descuento": "$40.000",
        "Observación": "",
        "Info": ""
    },
    {
        "Año": "2024",
        "Mes": "Septiembre",
        "Ciudad": "Santiago",
        "Día": "Viernes",
        "Institución Financiera": "Banco BCI",
        "Producto": "T. Crédito",
        "Marca de Tarjeta": "",
        "Segmento": "",
        "Local": "Pescados Capitales",
        "Descuento": "40%",
        "Tope Descuento": "$40.000",
        "Observación": "",
        "Info": ""
    },
    {
        "Año": "2024",
        "Mes": "Septiembre",
        "Ciudad": "Santiago",
        "Día": "Viernes",
        "Institución Financiera": "Banco BCI",
        "Producto": "T. Crédito",
        "Marca de Tarjeta": "",
        "Segmento": "",
        "Local": "Verde Sazón",
        "Descuento": "40%",
        "Tope Descuento": "$40.000",
        "Observación": "",
        "Info": ""
    },
    {
        "Año": "2024",
        "Mes": "Septiembre",
        "Ciudad": "Santiago",
        "Día": "Viernes",
        "Institución Financiera": "Banco BCI",
        "Producto": "T. Crédito",
        "Marca de Tarjeta": "",
        "Segmento": "BCI Plus Cashback",
        "Local": "Cocina De Javier",
        "Descuento": "50%",
        "Tope Descuento": "$40.000",
        "Observación": "",
        "Info": ""
    },
    {
        "Año": "2024",
        "Mes": "Septiembre",
        "Ciudad": "Santiago",
        "Día": "Lunes, Martes",
        "Institución Financiera": "Banco BCI",
        "Producto": "T. Crédito",
        "Marca de Tarjeta": "",
        "Segmento": "BCI Plus Cashback",
        "Local": "Pizza Nostra",
        "Descuento": "40%",
        "Tope Descuento": "$40.000",
        "Observación": "",
        "Info": ""
    },
    {
        "Año": "2024",
        "Mes": "Septiembre",
        "Ciudad": "Santiago",
        "Día": "Lunes, Miércoles, Viernes",
        "Institución Financiera": "Banco BCI",
        "Producto": "T. Crédito",
        "Marca de Tarjeta": "",
        "Segmento": "BCI Plus Cashback",
        "Local": "Cocina De Kaleta",
        "Descuento": "40%",
        "Tope Descuento": "$40.000",
        "Observación": "",
        "Info": ""
    },
    {
        "Año": "2024",
        "Mes": "Septiembre",
        "Ciudad": "Santiago",
        "Día": "Lunes, Miércoles, Viernes",
        "Institución Financiera": "Banco BCI",
        "Producto": "T. Crédito",
        "Marca de Tarjeta": "",
        "Segmento": "BCI Plus Cashback",
        "Local": "La Perla Del Pacífico",
        "Descuento": "40%",
        "Tope Descuento": "$40.000",
        "Observación": "",
        "Info": ""
    },
    {
        "Año": "2024",
        "Mes": "Septiembre",
        "Ciudad": "Santiago",
        "Día": "Lunes, Miércoles, Viernes",
        "Institución Financiera": "Banco BCI",
        "Producto": "T. Crédito",
        "Marca de Tarjeta": "",
        "Segmento": "BCI Plus Cashback",
        "Local": "Puerto Del Alto",
        "Descuento": "40%",
        "Tope Descuento": "$40.000",
        "Observación": "",
        "Info": ""
    },
    {
        "Año": "2024",
        "Mes": "Septiembre",
        "Ciudad": "Santiago",
        "Día": "Lunes, Miércoles, Viernes",
        "Institución Financiera": "Banco BCI",
        "Producto": "T. Crédito",
        "Marca de Tarjeta": "",
        "Segmento": "BCI Plus Cashback",
        "Local": "Trattoria Rita",
        "Descuento": "40%",
        "Tope Descuento": "$40.000",
        "Observación": "",
        "Info": ""
    },
    {
        "Año": "2024",
        "Mes": "Septiembre",
        "Ciudad": "Santiago",
        "Día": "Martes, Miércoles, Jueves",
        "Institución Financiera": "Banco BCI",
        "Producto": "T. Crédito",
        "Marca de Tarjeta": "",
        "Segmento": "BCI Plus Cashback",
        "Local": "Kento Sushi",
        "Descuento": "40%",
        "Tope Descuento": "$40.000",
        "Observación": "",
        "Info": ""
    },
    {
        "Año": "2024",
        "Mes": "Septiembre",
        "Ciudad": "Santiago",
        "Día": "Miércoles, Sábado",
        "Institución Financiera": "Banco BCI",
        "Producto": "T. Crédito",
        "Marca de Tarjeta": "",
        "Segmento": "BCI Plus Cashback",
        "Local": "Expendio Montt",
        "Descuento": "40%",
        "Tope Descuento": "$40.000",
        "Observación": "",
        "Info": ""
    },
    {
        "Año": "2024",
        "Mes": "Septiembre",
        "Ciudad": "Santiago",
        "Día": "Miércoles, Sábado",
        "Institución Financiera": "Banco BCI",
        "Producto": "T. Crédito",
        "Marca de Tarjeta": "",
        "Segmento": "BCI Plus Cashback",
        "Local": "Porfirio",
        "Descuento": "40%",
        "Tope Descuento": "$40.000",
        "Observación": "",
        "Info": ""
    },
    {
        "Año": "2024",
        "Mes": "Septiembre",
        "Ciudad": "Santiago",
        "Día": "Sábado, Domingo",
        "Institución Financiera": "Banco BCI",
        "Producto": "T. Crédito",
        "Marca de Tarjeta": "",
        "Segmento": "BCI Plus Cashback",
        "Local": "Caramagnola",
        "Descuento": "40%",
        "Tope Descuento": "$40.000",
        "Observación": "",
        "Info": ""
    },
    {
        "Año": "2024",
        "Mes": "Septiembre",
        "Ciudad": "Santiago",
        "Día": "Viernes, Sábado, Domingo",
        "Institución Financiera": "Banco BCI",
        "Producto": "T. Crédito",
        "Marca de Tarjeta": "",
        "Segmento": "BCI Plus Cashback",
        "Local": "Baza Los Trapenses",
        "Descuento": "40%",
        "Tope Descuento": "$40.000",
        "Observación": "",
        "Info": ""
    },
    {
        "Año": "2024",
        "Mes": "Septiembre",
        "Ciudad": "Santiago",
        "Día": "Viernes, Sábado, Domingo",
        "Institución Financiera": "Banco BCI",
        "Producto": "T. Crédito",
        "Marca de Tarjeta": "",
        "Segmento": "BCI Plus Cashback",
        "Local": "Puerto Del Alto",
        "Descuento": "40%",
        "Tope Descuento": "$40.000",
        "Observación": "",
        "Info": ""
    },
    {
        "Año": "2024",
        "Mes": "Septiembre",
        "Ciudad": "Santiago",
        "Día": "Lunes",
        "Institución Financiera": "Banco de Chile",
        "Producto": "T. Débito, T. Crédito",
        "Marca de Tarjeta": "VISA",
        "Segmento": "",
        "Local": "Al Pesto",
        "Descuento": "40%",
        "Tope Descuento": "$50.000",
        "Observación": "",
        "Info": ""
    },
    {
        "Año": "2024",
        "Mes": "Septiembre",
        "Ciudad": "Santiago",
        "Día": "Lunes",
        "Institución Financiera": "Banco de Chile",
        "Producto": "T. Débito, T. Crédito",
        "Marca de Tarjeta": "VISA",
        "Segmento": "",
        "Local": "Doña Paula",
        "Descuento": "40%",
        "Tope Descuento": "$50.000",
        "Observación": "",
        "Info": ""
    },
    {
        "Año": "2024",
        "Mes": "Septiembre",
        "Ciudad": "Santiago",
        "Día": "Martes",
        "Institución Financiera": "Banco de Chile",
        "Producto": "T. Débito, T. Crédito",
        "Marca de Tarjeta": "VISA",
        "Segmento": "",
        "Local": "La Cocina De Javier",
        "Descuento": "30%",
        "Tope Descuento": "$50.000",
        "Observación": "",
        "Info": ""
    },
    {
        "Año": "2024",
        "Mes": "Septiembre",
        "Ciudad": "Santiago",
        "Día": "Martes",
        "Institución Financiera": "Banco de Chile",
        "Producto": "T. Débito, T. Crédito",
        "Marca de Tarjeta": "VISA",
        "Segmento": "",
        "Local": "La Perla Del Pacífico",
        "Descuento": "40%",
        "Tope Descuento": "$50.000",
        "Observación": "",
        "Info": ""
    },
    {
        "Año": "2024",
        "Mes": "Septiembre",
        "Ciudad": "Santiago",
        "Día": "Martes",
        "Institución Financiera": "Banco de Chile",
        "Producto": "T. Débito, T. Crédito",
        "Marca de Tarjeta": "VISA",
        "Segmento": "",
        "Local": "Quercus",
        "Descuento": "40%",
        "Tope Descuento": "$50.000",
        "Observación": "",
        "Info": ""
    },
    {
        "Año": "2024",
        "Mes": "Septiembre",
        "Ciudad": "Santiago",
        "Día": "Miércoles",
        "Institución Financiera": "Banco de Chile",
        "Producto": "T. Débito, T. Crédito",
        "Marca de Tarjeta": "VISA",
        "Segmento": "",
        "Local": "Capogrossi",
        "Descuento": "40%",
        "Tope Descuento": "$50.000",
        "Observación": "",
        "Info": ""
    },
    {
        "Año": "2024",
        "Mes": "Septiembre",
        "Ciudad": "Santiago",
        "Día": "Jueves",
        "Institución Financiera": "Banco de Chile",
        "Producto": "T. Débito, T. Crédito",
        "Marca de Tarjeta": "VISA",
        "Segmento": "",
        "Local": "Brasas Del Arriero",
        "Descuento": "40%",
        "Tope Descuento": "$50.000",
        "Observación": "",
        "Info": ""
    },
    {
        "Año": "2024",
        "Mes": "Septiembre",
        "Ciudad": "Santiago",
        "Día": "Viernes",
        "Institución Financiera": "Banco de Chile",
        "Producto": "T. Débito, T. Crédito",
        "Marca de Tarjeta": "VISA",
        "Segmento": "",
        "Local": "Medanoso",
        "Descuento": "40%",
        "Tope Descuento": "$50.000",
        "Observación": "",
        "Info": ""
    },
    {
        "Año": "2024",
        "Mes": "Septiembre",
        "Ciudad": "Santiago",
        "Día": "Sábado",
        "Institución Financiera": "Banco de Chile",
        "Producto": "T. Débito, T. Crédito",
        "Marca de Tarjeta": "VISA",
        "Segmento": "",
        "Local": "Fechoría",
        "Descuento": "40%",
        "Tope Descuento": "$50.000",
        "Observación": "",
        "Info": ""
    },
    {
        "Año": "2024",
        "Mes": "Septiembre",
        "Ciudad": "Santiago",
        "Día": "Domingo",
        "Institución Financiera": "Banco de Chile",
        "Producto": "T. Débito, T. Crédito",
        "Marca de Tarjeta": "VISA",
        "Segmento": "",
        "Local": "La Calma De Rita",
        "Descuento": "40%",
        "Tope Descuento": "$50.000",
        "Observación": "",
        "Info": ""
    },
    {
        "Año": "2024",
        "Mes": "Septiembre",
        "Ciudad": "Santiago",
        "Día": "Martes",
        "Institución Financiera": "Banco Ripley",
        "Producto": "T. Crédito",
        "Marca de Tarjeta": "",
        "Segmento": "",
        "Local": "Cantina Montt",
        "Descuento": "40%",
        "Tope Descuento": "$40.000",
        "Observación": "",
        "Info": ""
    },
    {
        "Año": "2024",
        "Mes": "Septiembre",
        "Ciudad": "Santiago",
        "Día": "Miércoles",
        "Institución Financiera": "Banco Ripley",
        "Producto": "T. Crédito",
        "Marca de Tarjeta": "",
        "Segmento": "",
        "Local": "Nkiru",
        "Descuento": "40%",
        "Tope Descuento": "$40.000",
        "Observación": "",
        "Info": ""
    },
    {
        "Año": "2024",
        "Mes": "Septiembre",
        "Ciudad": "Santiago",
        "Día": "Jueves",
        "Institución Financiera": "Banco Ripley",
        "Producto": "T. Crédito",
        "Marca de Tarjeta": "",
        "Segmento": "",
        "Local": "Fukai",
        "Descuento": "40%",
        "Tope Descuento": "$40.000",
        "Observación": "",
        "Info": ""
    },
    {
        "Año": "2024",
        "Mes": "Septiembre",
        "Ciudad": "Santiago",
        "Día": "Jueves",
        "Institución Financiera": "Banco Ripley",
        "Producto": "T. Crédito",
        "Marca de Tarjeta": "",
        "Segmento": "",
        "Local": "Galpón Italia",
        "Descuento": "40%",
        "Tope Descuento": "$40.000",
        "Observación": "",
        "Info": ""
    },
    {
        "Año": "2024",
        "Mes": "Septiembre",
        "Ciudad": "Santiago",
        "Día": "Viernes",
        "Institución Financiera": "Banco Ripley",
        "Producto": "T. Crédito",
        "Marca de Tarjeta": "",
        "Segmento": "",
        "Local": "Castillo Hamburgo",
        "Descuento": "40%",
        "Tope Descuento": "$40.000",
        "Observación": "",
        "Info": ""
    },
    {
        "Año": "2024",
        "Mes": "Septiembre",
        "Ciudad": "Santiago",
        "Día": "Sábado",
        "Institución Financiera": "Banco Ripley",
        "Producto": "T. Crédito",
        "Marca de Tarjeta": "",
        "Segmento": "",
        "Local": "Majestic",
        "Descuento": "40%",
        "Tope Descuento": "$40.000",
        "Observación": "",
        "Info": ""
    },
    {
        "Año": "2024",
        "Mes": "Septiembre",
        "Ciudad": "Santiago",
        "Día": "Jueves, Viernes, Sábado",
        "Institución Financiera": "Tenpo",
        "Producto": "T. Crédito",
        "Marca de Tarjeta": "Mastecard",
        "Segmento": "",
        "Local": "Vicenzo",
        "Descuento": "30%",
        "Tope Descuento": "$100.000",
        "Observación": "",
        "Info": ""
    },
    {
        "Año": "2024",
        "Mes": "Septiembre",
        "Ciudad": "Santiago",
        "Día": "Lunes, Martes",
        "Institución Financiera": "Tenpo",
        "Producto": "T. Crédito",
        "Marca de Tarjeta": "Mastecard",
        "Segmento": "",
        "Local": "Barbazul",
        "Descuento": "30%",
        "Tope Descuento": "$100.000",
        "Observación": "",
        "Info": ""
    }
];
